<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_fa3VwL_kEeOE0tmaYDzcJw" name="BDMQueryProcess" version="10.0" author="Philippe" bonitaVersion="7.4.0" bonitaModelVersion="7.2.0-002" configId="ACED000574001F42444D517565727950726F63657373372E322E302D303032372E342E307370">
    <elements xmi:type="process:Pool" xmi:id="_fgWSsL_kEeOE0tmaYDzcJw" name="BDMQueryProcess" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="10.0">
      <elements xmi:type="process:Lane" xmi:id="_fnp0kL_kEeOE0tmaYDzcJw" name="Employee lane" actor="_fnmxQL_kEeOE0tmaYDzcJw">
        <elements xmi:type="process:Task" xmi:id="_foF5cL_kEeOE0tmaYDzcJw" name="Step1" outgoing="_R26LEL_wEeOE0tmaYDzcJw" incoming="_frQiML_kEeOE0tmaYDzcJw" useCardinality="true" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_foI8w7_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_foI8wb_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_foI8wL_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_foI8wr_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_foJj0L_kEeOE0tmaYDzcJw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_foJj0b_kEeOE0tmaYDzcJw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bD9F1DpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bD9F1TpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bD9F1jpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <transientData xmi:type="process:JavaObjectData" xmi:id="_QZdDsL_yEeOLaJXD99xx9w" name="listOfAllOrders" datasourceId="PAGEFLOW" dataType="_fa380L_kEeOE0tmaYDzcJw" className="java.util.List">
            <defaultValue xmi:type="expression:Expression" xmi:id="_dN_SMMavEeWStvAm3pigyA" name="PurchaseOrder.find" content="SELECT p&#xA;FROM PurchaseOrder p&#xA;ORDER BY p.persistenceId" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="java.util.List">
              <referencedElements xmi:type="expression:Expression" xmi:id="_dN_SMcavEeWStvAm3pigyA" name="startIndex" content="startIndex" type="QUERY_PARAM_TYPE" returnType="java.lang.Integer" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_dN_SMsavEeWStvAm3pigyA" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </referencedElements>
              <referencedElements xmi:type="expression:Expression" xmi:id="_dN_SM8avEeWStvAm3pigyA" name="maxResults" content="maxResults" type="QUERY_PARAM_TYPE" returnType="java.lang.Integer" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_dN_SNMavEeWStvAm3pigyA" name="20" content="20" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </referencedElements>
            </defaultValue>
          </transientData>
          <form xmi:type="form:Form" xmi:id="_xN3RwL_uEeOE0tmaYDzcJw" name="Step1" nLine="3">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_xN3Rwb_uEeOE0tmaYDzcJw" name="Submit1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_xN3Rwr_uEeOE0tmaYDzcJw" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_dN_5RcavEeWStvAm3pigyA" name="Submit1" content="Submit1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dN_5RsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:ListFormField" xmi:id="_yBl0wL_uEeOE0tmaYDzcJw" name="List1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_dN_5SsavEeWStvAm3pigyA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_dN_5S8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_dN_5TMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_dN_5TcavEeWStvAm3pigyA" name="getListOfBO" content="import com.company.model.PurchaseOrder;&#xD;&#xA;&#xD;&#xA;Map map = new HashMap();&#xD;&#xA;&#xD;&#xA;PurchaseOrder pOrder;&#xD;&#xA;&#xD;&#xA;Iterator it = listOfAllOrders.iterator();&#xD;&#xA;&#xD;&#xA;while (it.hasNext()) {&#xD;&#xA;&#x9;&#xD;&#xA;&#x9;pOrder = (PurchaseOrder)it.next();&#xD;&#xA;&#x9;map.put(pOrder.getClient(), pOrder.getPersistenceId());&#xD;&#xA;&#x9;&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return map;&#xD;&#xA; " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map"/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_dN_5TsavEeWStvAm3pigyA" name="empty_list" content="[]" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
              <tooltip xmi:type="expression:Expression" xmi:id="_dN_5T8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_dN_5UMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_dN_5UcavEeWStvAm3pigyA" name="List1" content="List1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dN_5UsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_yBmb2b_uEeOE0tmaYDzcJw">
                <leftOperand xmi:type="expression:Expression" xmi:id="_dN_5XcavEeWStvAm3pigyA" content=""/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_dN_5XsavEeWStvAm3pigyA" content=""/>
                <operator xmi:type="expression:Operator" xmi:id="_yBmb27_uEeOE0tmaYDzcJw" type="ASSIGNMENT" expression="="/>
              </action>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dN_5VMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dN_5VcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_dN_5VsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <tooltipForAdd xmi:type="expression:Expression" xmi:id="_dN_5V8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_dN_5WMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <tooltipForRemove xmi:type="expression:Expression" xmi:id="_dN_5WcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <exampleMessage xmi:type="expression:Expression" xmi:id="_dN_5WsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <defaultExpression xmi:type="expression:Expression" xmi:id="_dN_5W8avEeWStvAm3pigyA" name="" content="" interpreter="GROOVY" returnType="java.util.Collection"/>
              <defaultExpressionAfterEvent xmi:type="expression:Expression" xmi:id="_dN_5XMavEeWStvAm3pigyA" name="Empty list" content="[]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Collection"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_dN_5QMavEeWStvAm3pigyA" name="Step1" content="Step1" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_foJj0r_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_foJj07_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ofs6MBvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_dN_5YMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ofsTXBvNEeWwB5BI7jdhZw"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_fqqFQL_kEeOE0tmaYDzcJw" name="Start1" outgoing="_frQiML_kEeOE0tmaYDzcJw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_dN_5ZcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dN_5ZsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dN_5Z8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dN_5aMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_RkqkgL_wEeOE0tmaYDzcJw" name="Terminate end event1" incoming="_R26LEL_wEeOE0tmaYDzcJw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_dN_5acavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dN_5asavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dN_5a8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dN_5bMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_fwMskL_kEeOE0tmaYDzcJw" path="_fgWSsL_kEeOE0tmaYDzcJw/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_fkGKQr_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_fkGKQb_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_fwMsk7_kEeOE0tmaYDzcJw" path="_fgWSsL_kEeOE0tmaYDzcJw/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_fwMskb_kEeOE0tmaYDzcJw" path="_fgWSsL_kEeOE0tmaYDzcJw/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_fwNToL_kEeOE0tmaYDzcJw" path="_fgWSsL_kEeOE0tmaYDzcJw/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_fwMskr_kEeOE0tmaYDzcJw" path="_fgWSsL_kEeOE0tmaYDzcJw/html/consultation.html"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_k4QLgL_kEeOE0tmaYDzcJw" name="newOrder" dataType="_fa380r_kEeOE0tmaYDzcJw" className="com.company.model.PurchaseOrder"/>
      <form xmi:type="form:Form" xmi:id="_mvkScL_kEeOE0tmaYDzcJw" name="CreateOrders" nLine="3">
        <widgets xmi:type="form:Group" xmi:id="_mvkScb_kEeOE0tmaYDzcJw" name="newOrder1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_dN_5bcavEeWStvAm3pigyA" verticalSpan="2"/>
          <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_dN_5bsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_dOAgUMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_dOAgUcavEeWStvAm3pigyA" name="" content=""/>
          <afterEventExpression xmi:type="expression:Expression" xmi:id="_dOAgUsavEeWStvAm3pigyA" name="" content=""/>
          <tooltip xmi:type="expression:Expression" xmi:id="_dOAgU8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <helpMessage xmi:type="expression:Expression" xmi:id="_dOAgVMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_dOAgVcavEeWStvAm3pigyA" name="New Order" content="New Order" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dOAgVsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <action xmi:type="expression:Operation" xmi:id="_dOAgV8avEeWStvAm3pigyA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dOAgWMavEeWStvAm3pigyA"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dOAgWcavEeWStvAm3pigyA"/>
            <operator xmi:type="expression:Operator" xmi:id="_dOAgWsavEeWStvAm3pigyA" type="ASSIGNMENT" expression="="/>
          </action>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgW8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgXMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_dOAgXcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <tooltipForAdd xmi:type="expression:Expression" xmi:id="_dOAgXsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_dOAgX8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <tooltipForRemove xmi:type="expression:Expression" xmi:id="_dOAgYMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <widgets xmi:type="form:TextFormField" xmi:id="_mvk5gb_kEeOE0tmaYDzcJw" name="newOrder1_client1" maxLength="255">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_dOAgZMavEeWStvAm3pigyA"/>
            <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_dOAgZcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_dOAgZsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_dOAgZ8avEeWStvAm3pigyA" name="" content=""/>
            <afterEventExpression xmi:type="expression:Expression" xmi:id="_dOAgaMavEeWStvAm3pigyA" name="" content=""/>
            <tooltip xmi:type="expression:Expression" xmi:id="_dOAgacavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <helpMessage xmi:type="expression:Expression" xmi:id="_dOAgasavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_dOAga8avEeWStvAm3pigyA" name="Client" content="Client" returnTypeFixed="true"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dOAgbMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <action xmi:type="expression:Operation" xmi:id="_dOAgbcavEeWStvAm3pigyA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_dOAgbsavEeWStvAm3pigyA" name="newOrder" content="newOrder" type="TYPE_VARIABLE" returnType="com.company.model.PurchaseOrder">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dOAgb8avEeWStvAm3pigyA" name="newOrder" dataType="_fa380r_kEeOE0tmaYDzcJw" className="com.company.model.PurchaseOrder"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_dOAgcMavEeWStvAm3pigyA" name="field_newOrder1_client1" content="field_newOrder1_client1" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_mvk5jL_kEeOE0tmaYDzcJw" name="newOrder1_client1"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_dOAgcsavEeWStvAm3pigyA" type="JAVA_METHOD" expression="setClient">
                <inputTypes>java.lang.String</inputTypes>
              </operator>
            </action>
            <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgc8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgdMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_dOAgdcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <tooltipForAdd xmi:type="expression:Expression" xmi:id="_dOAgdsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_dOAgd8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <tooltipForRemove xmi:type="expression:Expression" xmi:id="_dOAgeMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <exampleMessage xmi:type="expression:Expression" xmi:id="_dOAgecavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          </widgets>
          <widgets xmi:type="form:TextAreaFormField" xmi:id="_mvk5mL_kEeOE0tmaYDzcJw" name="newOrder1_description1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_dOAgesavEeWStvAm3pigyA" line="1"/>
            <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_dOAge8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_dOAgfMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_dOAgfcavEeWStvAm3pigyA" name="" content=""/>
            <afterEventExpression xmi:type="expression:Expression" xmi:id="_dOAgfsavEeWStvAm3pigyA" name="" content=""/>
            <tooltip xmi:type="expression:Expression" xmi:id="_dOAgf8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <helpMessage xmi:type="expression:Expression" xmi:id="_dOAggMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_dOAggcavEeWStvAm3pigyA" name="Description" content="Description" returnTypeFixed="true"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dOAggsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            <action xmi:type="expression:Operation" xmi:id="_dOAgg8avEeWStvAm3pigyA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_dOAghMavEeWStvAm3pigyA" name="newOrder" content="newOrder" type="TYPE_VARIABLE" returnType="com.company.model.PurchaseOrder">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dOAghcavEeWStvAm3pigyA" name="newOrder" dataType="_fa380r_kEeOE0tmaYDzcJw" className="com.company.model.PurchaseOrder"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_dOAghsavEeWStvAm3pigyA" name="field_newOrder1_description1" content="field_newOrder1_description1" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextAreaFormField" xmi:id="_mvk5o7_kEeOE0tmaYDzcJw" name="newOrder1_description1"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_dOAgiMavEeWStvAm3pigyA" type="JAVA_METHOD" expression="setDescription">
                <inputTypes>java.lang.String</inputTypes>
              </operator>
            </action>
            <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgicavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_dOAgisavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <displayLabelForAdd xmi:type="expression:Expression" xmi:id="_dOAgi8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <tooltipForAdd xmi:type="expression:Expression" xmi:id="_dOAgjMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <displayLabelForRemove xmi:type="expression:Expression" xmi:id="_dOAgjcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <tooltipForRemove xmi:type="expression:Expression" xmi:id="_dOAgjsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
            <exampleMessage xmi:type="expression:Expression" xmi:id="_dOAgj8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          </widgets>
          <iterator xmi:type="form:GroupIterator" xmi:id="_shojsOGOEeOBRccffrPWDw" className="java.lang.Object"/>
        </widgets>
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_mvk5r7_kEeOE0tmaYDzcJw" name="Submit1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_mvk5sL_kEeOE0tmaYDzcJw" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_dN_5SMavEeWStvAm3pigyA" name="Submit1" content="Submit1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_dN_5ScavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_dN_5Q8avEeWStvAm3pigyA" name="Create Orders" content="Create Orders" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_fkGKRL_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_fkGKQ7_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ofsTSRvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_dN_5YcavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_fkGKRb_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ofsTShvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_dN_5YsavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_fkGKQL_kEeOE0tmaYDzcJw" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_frQiML_kEeOE0tmaYDzcJw" target="_foF5cL_kEeOE0tmaYDzcJw" source="_fqqFQL_kEeOE0tmaYDzcJw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_frRwUL_kEeOE0tmaYDzcJw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dOAgkcavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R26LEL_wEeOE0tmaYDzcJw" target="_RkqkgL_wEeOE0tmaYDzcJw" source="_foF5cL_kEeOE0tmaYDzcJw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R26LEb_wEeOE0tmaYDzcJw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dOAgk8avEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_fnmxQL_kEeOE0tmaYDzcJw" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_eWYDgMYyEeOeMsoWvEjWOg" name="Selenium" version="6.3.0-002" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_eWYqosYyEeOeMsoWvEjWOg">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_eWYqo8YyEeOeMsoWvEjWOg" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_eWYqpcYyEeOeMsoWvEjWOg">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_eWYqp8YyEeOeMsoWvEjWOg"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_eWYqpsYyEeOeMsoWvEjWOg"/>
            <users xmi:type="actormapping:Users" xmi:id="_eWYqpMYyEeOeMsoWvEjWOg"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqkMYyEeOeMsoWvEjWOg" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqkcYyEeOeMsoWvEjWOg" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqksYyEeOeMsoWvEjWOg" id="DATA_TYPES">
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqk8YyEeOeMsoWvEjWOg" key="org.bonitasoft.budgeting.jar" value="org.bonitasoft.budgeting.jar" exported="false" type="JAR"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqlMYyEeOeMsoWvEjWOg" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqlcYyEeOeMsoWvEjWOg" key="BudgetingMapper.groovy" value="BudgetingMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqlsYyEeOeMsoWvEjWOg" key="BudgetingUtil.groovy" value="BudgetingUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYql8YyEeOeMsoWvEjWOg" key="BudgetingVersion.groovy" value="BudgetingVersion.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqmMYyEeOeMsoWvEjWOg" key="CustomerSupportMapper.groovy" value="CustomerSupportMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqmcYyEeOeMsoWvEjWOg" key="CustomerSupportUtil.groovy" value="CustomerSupportUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqmsYyEeOeMsoWvEjWOg" key="CustomerSupportVersion.groovy" value="CustomerSupportVersion.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqm8YyEeOeMsoWvEjWOg" key="LMMapper.groovy" value="LMMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqnMYyEeOeMsoWvEjWOg" key="LeaveManagementMapper.groovy" value="LeaveManagementMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqncYyEeOeMsoWvEjWOg" key="MyScript.groovy" value="MyScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqnsYyEeOeMsoWvEjWOg" key="OnboardingMapper.groovy" value="OnboardingMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqn8YyEeOeMsoWvEjWOg" key="OnboardingUtil.groovy" value="OnboardingUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqoMYyEeOeMsoWvEjWOg" key="Version.groovy" value="Version.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqocYyEeOeMsoWvEjWOg" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqqMYyEeOeMsoWvEjWOg" id="DATA_TYPES">
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqqcYyEeOeMsoWvEjWOg" key="org.bonitasoft.budgeting.jar" value="org.bonitasoft.budgeting.jar" exported="false" type="JAR"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqqsYyEeOeMsoWvEjWOg" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqq8YyEeOeMsoWvEjWOg" key="BudgetingMapper.groovy" value="BudgetingMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqrMYyEeOeMsoWvEjWOg" key="BudgetingUtil.groovy" value="BudgetingUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqrcYyEeOeMsoWvEjWOg" key="BudgetingVersion.groovy" value="BudgetingVersion.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqrsYyEeOeMsoWvEjWOg" key="CustomerSupportMapper.groovy" value="CustomerSupportMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqr8YyEeOeMsoWvEjWOg" key="CustomerSupportUtil.groovy" value="CustomerSupportUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqsMYyEeOeMsoWvEjWOg" key="CustomerSupportVersion.groovy" value="CustomerSupportVersion.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqscYyEeOeMsoWvEjWOg" key="LMMapper.groovy" value="LMMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqssYyEeOeMsoWvEjWOg" key="LeaveManagementMapper.groovy" value="LeaveManagementMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqs8YyEeOeMsoWvEjWOg" key="MyScript.groovy" value="MyScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqtMYyEeOeMsoWvEjWOg" key="OnboardingMapper.groovy" value="OnboardingMapper.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqtcYyEeOeMsoWvEjWOg" key="OnboardingUtil.groovy" value="OnboardingUtil.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_eWYqtsYyEeOeMsoWvEjWOg" key="Version.groovy" value="Version.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYqt8YyEeOeMsoWvEjWOg" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_eWYquMYyEeOeMsoWvEjWOg" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_ofsTSxvNEeWwB5BI7jdhZw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_fkE8IL_kEeOE0tmaYDzcJw">
        <name xmi:type="expression:Expression" xmi:id="_dOBHfsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dOBHf8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_fkFjMr_kEeOE0tmaYDzcJw">
        <name xmi:type="expression:Expression" xmi:id="_dOBHgMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dOBHgcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_fkFjNb_kEeOE0tmaYDzcJw">
        <name xmi:type="expression:Expression" xmi:id="_dOBHgsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dOBHg8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_fkFjOL_kEeOE0tmaYDzcJw">
        <name xmi:type="expression:Expression" xmi:id="_dOBucMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dOBuccavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_fkFjO7_kEeOE0tmaYDzcJw">
        <name xmi:type="expression:Expression" xmi:id="_dOBucsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dOBuc8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <formMapping xmi:type="process:FormMapping" xmi:id="_ofsTMBvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_dN_5Y8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </formMapping>
    <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ofsTMRvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_dN_5ZMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </overviewFormMapping>
    <datatypes xmi:type="process:BooleanType" xmi:id="_fa3Vwb_kEeOE0tmaYDzcJw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_fa3Vwr_kEeOE0tmaYDzcJw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_fa3Vw7_kEeOE0tmaYDzcJw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_fa3VxL_kEeOE0tmaYDzcJw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_fa3Vxb_kEeOE0tmaYDzcJw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_fa3Vxr_kEeOE0tmaYDzcJw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_fa380L_kEeOE0tmaYDzcJw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_fa380b_kEeOE0tmaYDzcJw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_fa380r_kEeOE0tmaYDzcJw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_fa3807_kEeOE0tmaYDzcJw" type="Process" element="_fa3VwL_kEeOE0tmaYDzcJw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_fkz78L_kEeOE0tmaYDzcJw" type="2007" element="_fgWSsL_kEeOE0tmaYDzcJw">
      <children xmi:type="notation:DecorationNode" xmi:id="_fk4NYL_kEeOE0tmaYDzcJw" type="5008" element="_fgWSsL_kEeOE0tmaYDzcJw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_fk4NYb_kEeOE0tmaYDzcJw" type="7001" element="_fgWSsL_kEeOE0tmaYDzcJw">
        <children xmi:type="notation:Node" xmi:id="_dOBumcavEeWStvAm3pigyA" type="3007" element="_fnp0kL_kEeOE0tmaYDzcJw">
          <children xmi:type="notation:DecorationNode" xmi:id="_fns34L_kEeOE0tmaYDzcJw" type="5007" element="_fnp0kL_kEeOE0tmaYDzcJw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_fns34b_kEeOE0tmaYDzcJw" type="7002" element="_fnp0kL_kEeOE0tmaYDzcJw">
            <children xmi:type="notation:Shape" xmi:id="_foT74L_kEeOE0tmaYDzcJw" type="3005" element="_foF5cL_kEeOE0tmaYDzcJw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dOBupMavEeWStvAm3pigyA" type="5005" element="_foF5cL_kEeOE0tmaYDzcJw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_foT74b_kEeOE0tmaYDzcJw" x="160" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fqshgL_kEeOE0tmaYDzcJw" type="3002" element="_fqqFQL_kEeOE0tmaYDzcJw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dOBupsavEeWStvAm3pigyA" type="5024" element="_fqqFQL_kEeOE0tmaYDzcJw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fqshg7_kEeOE0tmaYDzcJw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fqshgb_kEeOE0tmaYDzcJw" x="60" y="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Rktn0L_wEeOE0tmaYDzcJw" type="3062" element="_RkqkgL_wEeOE0tmaYDzcJw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dOBuqcavEeWStvAm3pigyA" type="5090" element="_RkqkgL_wEeOE0tmaYDzcJw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Rktn07_wEeOE0tmaYDzcJw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Rktn0b_wEeOE0tmaYDzcJw" x="347" y="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_fnsQ0b_kEeOE0tmaYDzcJw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_fnsQ0r_kEeOE0tmaYDzcJw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_fnsQ07_kEeOE0tmaYDzcJw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_fns34r_kEeOE0tmaYDzcJw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fnsQ1L_kEeOE0tmaYDzcJw" x="45" y="10" width="1104" height="161"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_fkz78b_kEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_fkz78r_kEeOE0tmaYDzcJw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_fkz787_kEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_fk5bgL_kEeOE0tmaYDzcJw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fkz79L_kEeOE0tmaYDzcJw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_fa381L_kEeOE0tmaYDzcJw"/>
    <edges xmi:type="notation:Connector" xmi:id="_frWo0L_kEeOE0tmaYDzcJw" type="4001" element="_frQiML_kEeOE0tmaYDzcJw" source="_fqshgL_kEeOE0tmaYDzcJw" target="_foT74L_kEeOE0tmaYDzcJw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dOCVkcavEeWStvAm3pigyA" type="6001" element="_frQiML_kEeOE0tmaYDzcJw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dOCVksavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dOCVk8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_frWo0r_kEeOE0tmaYDzcJw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_R26yIL_wEeOE0tmaYDzcJw" type="4001" element="_R26LEL_wEeOE0tmaYDzcJw" source="_foT74L_kEeOE0tmaYDzcJw" target="_Rktn0L_wEeOE0tmaYDzcJw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dOCVlcavEeWStvAm3pigyA" type="6001" element="_R26LEL_wEeOE0tmaYDzcJw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dOCVlsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dOCVl8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R26yIr_wEeOE0tmaYDzcJw" points="[0, 3, -90, 0]$[87, 3, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_R291cL_wEeOE0tmaYDzcJw" id="(1.0,0.52)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_R291cb_wEeOE0tmaYDzcJw" id="(0.1,0.6)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_mvvRkL_kEeOE0tmaYDzcJw" type="Form" element="_mvkScL_kEeOE0tmaYDzcJw" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_mvvRkb_kEeOE0tmaYDzcJw"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_k711kL_lEeOE0tmaYDzcJw" type="Form" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_k9VqYL_lEeOE0tmaYDzcJw" type="2126">
      <children xmi:type="notation:DecorationNode" xmi:id="_k9WRcL_lEeOE0tmaYDzcJw" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_k9VqYb_lEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_k9VqYr_lEeOE0tmaYDzcJw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_k9VqY7_lEeOE0tmaYDzcJw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k9VqZL_lEeOE0tmaYDzcJw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_mGE0EL_lEeOE0tmaYDzcJw" type="2116" fontName="Segoe UI">
      <children xmi:type="notation:DecorationNode" xmi:id="_dOCVgcavEeWStvAm3pigyA" type="5152"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mGE0Eb_lEeOE0tmaYDzcJw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_k711kb_lEeOE0tmaYDzcJw"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_pMICML_pEeOE0tmaYDzcJw" type="Form" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_pMhDwL_pEeOE0tmaYDzcJw" type="2120" fontName="Segoe UI">
      <children xmi:type="notation:DecorationNode" xmi:id="_dOCVg8avEeWStvAm3pigyA" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pMhDwb_pEeOE0tmaYDzcJw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_pMhDw7_pEeOE0tmaYDzcJw" type="2125" fontName="Segoe UI">
      <children xmi:type="notation:Shape" xmi:id="_pMkuIL_pEeOE0tmaYDzcJw" type="3112" fontName="Segoe UI">
        <children xmi:type="notation:DecorationNode" xmi:id="_dOCVicavEeWStvAm3pigyA" type="5172"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pMkuIb_pEeOE0tmaYDzcJw"/>
      </children>
      <children xmi:type="notation:Shape" xmi:id="_pMkuI7_pEeOE0tmaYDzcJw" type="3113" fontName="Segoe UI">
        <children xmi:type="notation:DecorationNode" xmi:id="_dOCVi8avEeWStvAm3pigyA" type="5173"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pMkuJL_pEeOE0tmaYDzcJw"/>
      </children>
      <children xmi:type="notation:Shape" xmi:id="_tBApEL_pEeOE0tmaYDzcJw" type="3112" fontName="Segoe UI">
        <children xmi:type="notation:DecorationNode" xmi:id="_dOCVjcavEeWStvAm3pigyA" type="5172"/>
        <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tBApEb_pEeOE0tmaYDzcJw"/>
      </children>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pMhq0L_pEeOE0tmaYDzcJw"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_pMhq0b_pEeOE0tmaYDzcJw" type="2126">
      <children xmi:type="notation:DecorationNode" xmi:id="_pMhq1r_pEeOE0tmaYDzcJw" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_pMhq0r_pEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_pMhq07_pEeOE0tmaYDzcJw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_pMhq1L_pEeOE0tmaYDzcJw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pMhq1b_pEeOE0tmaYDzcJw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_pMICMb_pEeOE0tmaYDzcJw"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_xN7jML_uEeOE0tmaYDzcJw" type="Form" element="_xN3RwL_uEeOE0tmaYDzcJw" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_xONQAL_uEeOE0tmaYDzcJw" type="2126" element="_xN3Rwb_uEeOE0tmaYDzcJw">
      <children xmi:type="notation:DecorationNode" xmi:id="_xON3EL_uEeOE0tmaYDzcJw" type="5160" element="_xN3Rwb_uEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_xONQAb_uEeOE0tmaYDzcJw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_xONQAr_uEeOE0tmaYDzcJw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_xONQA7_uEeOE0tmaYDzcJw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xONQBL_uEeOE0tmaYDzcJw"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_yBnp8L_uEeOE0tmaYDzcJw" type="2116" element="_yBl0wL_uEeOE0tmaYDzcJw" fontName="Segoe UI">
      <children xmi:type="notation:DecorationNode" xmi:id="_dOCVj8avEeWStvAm3pigyA" type="5152" element="_yBl0wL_uEeOE0tmaYDzcJw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBnp8b_uEeOE0tmaYDzcJw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_xN7jMb_uEeOE0tmaYDzcJw"/>
  </notation:Diagram>
</xmi:XMI>
