<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_2BFJsS_5EeKnBYGJ1mXUfw" name="Buy a mini extended" version="6.1" author="truc" bonitaVersion="7.8.0" bonitaModelVersion="7.8.0-002" configId="ACED00057400234275792061206D696E6920657874656E646564372E382E302D303032372E382E307370">
    <elements xmi:type="process:Pool" xmi:id="_2BFJsi_5EeKnBYGJ1mXUfw" name="Buy a mini extended" version="6.1">
      <elements xmi:type="process:Lane" xmi:id="_2BFJsy_5EeKnBYGJ1mXUfw" name="Customer" actor="_2BL3jC_5EeKnBYGJ1mXUfw">
        <elements xmi:type="process:Task" xmi:id="_2BFJtC_5EeKnBYGJ1mXUfw" name="Model choice" outgoing="_2BL3by_5EeKnBYGJ1mXUfw" incoming="_2BL3Yy_5EeKnBYGJ1mXUfw _2BL3dS_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2BFJtS_5EeKnBYGJ1mXUfw" name="" content=""/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2BFJti_5EeKnBYGJ1mXUfw" content=""/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2BFJty_5EeKnBYGJ1mXUfw" content=""/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2BFJuy_5EeKnBYGJ1mXUfw" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2BFJvC_5EeKnBYGJ1mXUfw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBPzpTEeSntPZ4lnT8Jg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBQDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBQTpTEeSntPZ4lnT8Jg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ooj7hBvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUne08avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ooj7gxvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtdrQwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_2BGX4S_5EeKnBYGJ1mXUfw" name="Start" outgoing="_2BL3Yy_5EeKnBYGJ1mXUfw"/>
        <elements xmi:type="process:ServiceTask" xmi:id="_2BGX4y_5EeKnBYGJ1mXUfw" name="Availability check" outgoing="_2BL3aS_5EeKnBYGJ1mXUfw" incoming="_2BL3ci_5EeKnBYGJ1mXUfw" useCardinality="true">
          <connectors xmi:type="process:Connector" xmi:id="_2BGX5S_5EeKnBYGJ1mXUfw" name="checkModelAvailability" definitionId="MiniStockCheck" event="ON_ENTER" definitionVersion="1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_2BGX7S_5EeKnBYGJ1mXUfw" definitionId="MiniStockCheck" version="1.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_2BGX7i_5EeKnBYGJ1mXUfw" key="model">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF7cavEeWStvAm3pigyA" name="carType" content="carType" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_9mxIAQwYEei-AeSrpwoQZQ" name="carType" dataType="_2BL3mS_5EeKnBYGJ1mXUfw"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_dUoFx8avEeWStvAm3pigyA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_dUoFyMavEeWStvAm3pigyA" name="available" content="available" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="process:Data" xmi:id="_9mwhKwwYEei-AeSrpwoQZQ" name="available" dataType="_2BL3jS_5EeKnBYGJ1mXUfw"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_dUoFysavEeWStvAm3pigyA" name="isAvailable" content="isAvailable" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_2BGX7C_5EeKnBYGJ1mXUfw" name="isAvailable" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_dUoFzMavEeWStvAm3pigyA" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dUoFusavEeWStvAm3pigyA" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dUoFu8avEeWStvAm3pigyA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dUoFvMavEeWStvAm3pigyA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dUoFvcavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dUoFvsavEeWStvAm3pigyA" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2BGX9y_5EeKnBYGJ1mXUfw" name="Order" outgoing="_2BL3hC_5EeKnBYGJ1mXUfw" incoming="_2BL3gS_5EeKnBYGJ1mXUfw" useCardinality="true">
          <connectors xmi:type="process:Connector" xmi:id="_2BGX-S_5EeKnBYGJ1mXUfw" name="dueDate" definitionId="MiniDueDate" event="ON_ENTER" definitionVersion="1.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_2BGYAS_5EeKnBYGJ1mXUfw" definitionId="MiniDueDate" version="1.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_2BGYAi_5EeKnBYGJ1mXUfw" key="model">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF78avEeWStvAm3pigyA" name="carType" content="carType" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_9mxIAwwYEei-AeSrpwoQZQ" name="carType" dataType="_2BL3mS_5EeKnBYGJ1mXUfw"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_dUoFzsavEeWStvAm3pigyA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_dUoFz8avEeWStvAm3pigyA" name="dueDate" content="dueDate" type="TYPE_VARIABLE" returnType="java.util.Date">
                <referencedElements xmi:type="process:Data" xmi:id="_9mwhMgwYEei-AeSrpwoQZQ" name="dueDate" dataType="_2BL3ji_5EeKnBYGJ1mXUfw"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_dUoF0cavEeWStvAm3pigyA" name="dueDate" content="dueDate" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Date">
                <referencedElements xmi:type="definition:Output" xmi:id="_2BGYAC_5EeKnBYGJ1mXUfw" name="dueDate" type="java.util.Date"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_dUoF08avEeWStvAm3pigyA" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dUoFwcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dUoFwsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dUoFw8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dUoFxMavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dUoFxcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_2BGYBi_5EeKnBYGJ1mXUfw" name="Order finished" incoming="_2BL3hy_5EeKnBYGJ1mXUfw"/>
        <elements xmi:type="process:Task" xmi:id="_2BGYCC_5EeKnBYGJ1mXUfw" name="Accessories" outgoing="_2BL3ci_5EeKnBYGJ1mXUfw" incoming="_2BL3Zi_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2BGYCi_5EeKnBYGJ1mXUfw" content=""/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2BGYCy_5EeKnBYGJ1mXUfw" content=""/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2BGYDC_5EeKnBYGJ1mXUfw" content=""/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bGSBSTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bGSBSjpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBSzpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBTDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBTTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ooj7khvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUne1MavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ooj7kRvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtdvAwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2BHmLC_5EeKnBYGJ1mXUfw" name="Color selection" outgoing="_2BL3Zi_5EeKnBYGJ1mXUfw" incoming="_2BL3by_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2BHmLi_5EeKnBYGJ1mXUfw"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2BHmLy_5EeKnBYGJ1mXUfw"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2BHmMC_5EeKnBYGJ1mXUfw" content=""/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bGSBVTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bGSBVjpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBVzpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBWDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBWTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ookiWhvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUne1cavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ookiWRvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtdywwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2BI0WS_5EeKnBYGJ1mXUfw" name="Availability info" outgoing="_2BL3bC_5EeKnBYGJ1mXUfw" incoming="_2BL3aS_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <loopCondition xmi:type="expression:Expression" xmi:id="_bGSBXTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bGSBXjpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBXzpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBYDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBYTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ookiZBvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUoFsMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ookiYxvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtd1gwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2BJbSS_5EeKnBYGJ1mXUfw" name="Payment options" outgoing="_2BL3gS_5EeKnBYGJ1mXUfw" incoming="_2BL3ei_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <loopCondition xmi:type="expression:Expression" xmi:id="_bGSBZTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bGSBZjpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBZzpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBaDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBaTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ookibhvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUoFscavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ookibRvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtd4QwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2BJbdi_5EeKnBYGJ1mXUfw" name="Recap" outgoing="_2BL3hy_5EeKnBYGJ1mXUfw" incoming="_2BL3hC_5EeKnBYGJ1mXUfw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xkgCgDVQEeKBRMXNIgGKDQ" content=""/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xlVwADVQEeKBRMXNIgGKDQ" content=""/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xmBFcDVQEeKBRMXNIgGKDQ" content=""/>
          <data xmi:type="process:Data" xmi:id="_2BJbeC_5EeKnBYGJ1mXUfw" name="displayDate" dataType="_2BL3ky_5EeKnBYGJ1mXUfw">
            <defaultValue xmi:type="expression:Expression" xmi:id="_dUneoMavEeWStvAm3pigyA" name="displayDate" content="import org.joda.time.DateTime;&#xA;&#xA;def dt = new DateTime(dueDate.getTime());&#xA;dt.toString(&quot;dd-MM-yyyy&quot;)&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:Data" xmi:id="_9mv58gwYEei-AeSrpwoQZQ" name="dueDate" dataType="_2BL3ji_5EeKnBYGJ1mXUfw"/>
            </defaultValue>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_dZip4HRuEeKGI7Elg3IrIQ" documentation="Email sent to user confirming order details" name="Order_confirmation" definitionId="email" event="ON_FINISH" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_dZjQ83RuEeKGI7Elg3IrIQ" definitionId="email" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjQ9HRuEeKGI7Elg3IrIQ" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF8cavEeWStvAm3pigyA" name="smtpHost" content="smtpHost" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjQ9nRuEeKGI7Elg3IrIQ" name="smtpHost" value="" typeClassname="java.lang.String" description="SMTP host"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjQ93RuEeKGI7Elg3IrIQ" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF88avEeWStvAm3pigyA" name="smtpPort" content="smtpPort" type="TYPE_PARAMETER" returnType="java.lang.Integer" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjQ-XRuEeKGI7Elg3IrIQ" name="smtpPort" value="" typeClassname="java.lang.Integer" description="SMTP port"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjQ-nRuEeKGI7Elg3IrIQ" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF9cavEeWStvAm3pigyA" name="smtpSecurity" content="smtpSecurity" type="TYPE_PARAMETER" returnType="java.lang.Boolean" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjQ_HRuEeKGI7Elg3IrIQ" name="smtpSecurity" value="" typeClassname="java.lang.Boolean" description="Use SSL for SMTP"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjQ_XRuEeKGI7Elg3IrIQ" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF98avEeWStvAm3pigyA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjQ_3RuEeKGI7Elg3IrIQ" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF-MavEeWStvAm3pigyA" name="fromAddress" content="fromAddress" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjRAXRuEeKGI7Elg3IrIQ" name="fromAddress" value="" typeClassname="java.lang.String" description="From address of email confirming order"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRAnRuEeKGI7Elg3IrIQ" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF-savEeWStvAm3pigyA" name="authPassword" content="authPassword" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjRBHRuEeKGI7Elg3IrIQ" name="authPassword" value="" typeClassname="java.lang.String" description="Password for email authentication"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRBXRuEeKGI7Elg3IrIQ" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF_MavEeWStvAm3pigyA" name="fromAddress" content="fromAddress" type="TYPE_PARAMETER" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_dZjRB3RuEeKGI7Elg3IrIQ" name="fromAddress" value="" typeClassname="java.lang.String" description="From address of email confirming order"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRCHRuEeKGI7Elg3IrIQ" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_dUoF_savEeWStvAm3pigyA" name="buyerEmail" content="buyerEmail" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_9mxIEgwYEei-AeSrpwoQZQ" documentation="Email address of buyer" name="buyerEmail" dataType="_2BL3ky_5EeKnBYGJ1mXUfw"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRDHRuEeKGI7Elg3IrIQ" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGAMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRDnRuEeKGI7Elg3IrIQ" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGAcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjREHRuEeKGI7Elg3IrIQ" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGAsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjREnRuEeKGI7Elg3IrIQ" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGA8avEeWStvAm3pigyA" name="mailSubject" content="&quot;Confirmation of your new Mini order&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRFHRuEeKGI7Elg3IrIQ" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGBMavEeWStvAm3pigyA" name="Your Mini will be delivered on displayDate.&#xD;&#xA;&#xD;&#xA;Have fun with your new Mini!" content="Your Mini will be delivered on ${displayDate}.&#xD;&#xA;&#xD;&#xA;Have fun with your new Mini!" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_dUoGBcavEeWStvAm3pigyA" name="displayDate" content="displayDate" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_9mxIGQwYEei-AeSrpwoQZQ" name="displayDate" dataType="_2BL3ky_5EeKnBYGJ1mXUfw"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZjRG3RuEeKGI7Elg3IrIQ" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGB8avEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZj4AHRuEeKGI7Elg3IrIQ" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_dZj4AXRuEeKGI7Elg3IrIQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZj4AnRuEeKGI7Elg3IrIQ" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_dUoGCcavEeWStvAm3pigyA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_dZj4BHRuEeKGI7Elg3IrIQ" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_dZj4BXRuEeKGI7Elg3IrIQ"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_dUoF1cavEeWStvAm3pigyA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_dUoF1savEeWStvAm3pigyA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_dUoF18avEeWStvAm3pigyA" name="isSent" content="isSent" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_dZjQ8nRuEeKGI7Elg3IrIQ" name="isSent" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_dUoF2cavEeWStvAm3pigyA" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2BKCZy_5EeKnBYGJ1mXUfw" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2BKCaC_5EeKnBYGJ1mXUfw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bGSBdDpTEeSntPZ4lnT8Jg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bGSBdTpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bGSBdjpTEeSntPZ4lnT8Jg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ookifRvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_dUoFssavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ookifBvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9mtd8QwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_2BKpjy_5EeKnBYGJ1mXUfw" name="Is available" outgoing="_2BL3dS_5EeKnBYGJ1mXUfw _2BL3ei_5EeKnBYGJ1mXUfw" incoming="_2BL3bC_5EeKnBYGJ1mXUfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dUpUI8avEeWStvAm3pigyA"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dUpUJMavEeWStvAm3pigyA"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dUpUJcavEeWStvAm3pigyA" content=""/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_2BKplS_5EeKnBYGJ1mXUfw" name="availabilityMessage" dataType="_2BL3ky_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneosavEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BKply_5EeKnBYGJ1mXUfw" name="available" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneo8avEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQUS_5EeKnBYGJ1mXUfw" name="body_color" dataType="_2BL3mi_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnepMavEeWStvAm3pigyA" name="Chili red" content="Chili red"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQUy_5EeKnBYGJ1mXUfw" name="boseAudioSysOption" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnepcavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQVS_5EeKnBYGJ1mXUfw" name="carModel" dataType="_2BL3my_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnepsavEeWStvAm3pigyA" name="Mini Clubman" content="Mini Clubman"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQVy_5EeKnBYGJ1mXUfw" name="chromeLineOption" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnep8avEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQWS_5EeKnBYGJ1mXUfw" name="dueDate" dataType="_2BL3ji_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneqMavEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQWy_5EeKnBYGJ1mXUfw" name="gpsOption" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneqcavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQXS_5EeKnBYGJ1mXUfw" name="leatherSeatOption" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneqsavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQXy_5EeKnBYGJ1mXUfw" name="mirrorColor" dataType="_2BL3mC_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUneq8avEeWStvAm3pigyA" name="Black" content="Black"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQYS_5EeKnBYGJ1mXUfw" name="carType" dataType="_2BL3mS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnerMavEeWStvAm3pigyA" name="Cooper S" content="Cooper S"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQYy_5EeKnBYGJ1mXUfw" name="roofColor" dataType="_2BL3mC_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnercavEeWStvAm3pigyA" name="White" content="White"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQZS_5EeKnBYGJ1mXUfw" name="stripesColor" dataType="_2BL3ly_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnersavEeWStvAm3pigyA" name="White" content="White"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQZy_5EeKnBYGJ1mXUfw" name="wheelsOption" dataType="_2BL3nC_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUner8avEeWStvAm3pigyA" name="17' Alloy" content="17' Alloy"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQaS_5EeKnBYGJ1mXUfw" name="invoiceNumber" dataType="_2BL3ky_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnesMavEeWStvAm3pigyA"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQay_5EeKnBYGJ1mXUfw" name="isOrdered" dataType="_2BL3jS_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnescavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQbS_5EeKnBYGJ1mXUfw" name="paymentOption" dataType="_2BL3li_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnessavEeWStvAm3pigyA" name="Mini financial services solution" content="Mini financial services solution"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2BLQby_5EeKnBYGJ1mXUfw" documentation="Email address of buyer" name="buyerEmail" dataType="_2BL3ky_5EeKnBYGJ1mXUfw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dUnes8avEeWStvAm3pigyA" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ooj7ahvNEeWwB5BI7jdhZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_dUoFs8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ooj7axvNEeWwB5BI7jdhZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_dUoFtMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3Yy_5EeKnBYGJ1mXUfw" target="_2BFJtC_5EeKnBYGJ1mXUfw" source="_2BGX4S_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3ZC_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUpUJ8avEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3Zi_5EeKnBYGJ1mXUfw" target="_2BGYCC_5EeKnBYGJ1mXUfw" source="_2BHmLC_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3Zy_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUpUKcavEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3aS_5EeKnBYGJ1mXUfw" target="_2BI0WS_5EeKnBYGJ1mXUfw" source="_2BGX4y_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3ai_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUpUK8avEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3bC_5EeKnBYGJ1mXUfw" target="_2BKpjy_5EeKnBYGJ1mXUfw" source="_2BI0WS_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3bS_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUpULcavEeWStvAm3pigyA"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3by_5EeKnBYGJ1mXUfw" target="_2BHmLC_5EeKnBYGJ1mXUfw" source="_2BFJtC_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3cC_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp64cavEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3ci_5EeKnBYGJ1mXUfw" target="_2BGX4y_5EeKnBYGJ1mXUfw" source="_2BGYCC_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3cy_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp648avEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3dS_5EeKnBYGJ1mXUfw" name="No" target="_2BFJtC_5EeKnBYGJ1mXUfw" source="_2BKpjy_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3di_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp65cavEeWStvAm3pigyA" name="NotAvailable" content="!available" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
          <referencedElements xmi:type="process:Data" xmi:id="_9myWVgwYEei-AeSrpwoQZQ" name="available" dataType="_2BL3jS_5EeKnBYGJ1mXUfw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3ei_5EeKnBYGJ1mXUfw" name="Yes" target="_2BJbSS_5EeKnBYGJ1mXUfw" source="_2BKpjy_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3ey_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp66MavEeWStvAm3pigyA" name="isAvailable" content="available &amp;&amp; isOrdered" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
          <referencedElements xmi:type="process:Data" xmi:id="_9myWWQwYEei-AeSrpwoQZQ" name="isOrdered" dataType="_2BL3jS_5EeKnBYGJ1mXUfw"/>
          <referencedElements xmi:type="process:Data" xmi:id="_9myWWgwYEei-AeSrpwoQZQ" name="available" dataType="_2BL3jS_5EeKnBYGJ1mXUfw"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3gS_5EeKnBYGJ1mXUfw" target="_2BGX9y_5EeKnBYGJ1mXUfw" source="_2BJbSS_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3gi_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp67MavEeWStvAm3pigyA" content=""/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3hC_5EeKnBYGJ1mXUfw" target="_2BJbdi_5EeKnBYGJ1mXUfw" source="_2BGX9y_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3hS_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp67savEeWStvAm3pigyA"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2BL3hy_5EeKnBYGJ1mXUfw" target="_2BGYBi_5EeKnBYGJ1mXUfw" source="_2BJbdi_5EeKnBYGJ1mXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2BL3iC_5EeKnBYGJ1mXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dUp68MavEeWStvAm3pigyA" content=""/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_2BL3jC_5EeKnBYGJ1mXUfw" documentation="The customer actor involved in this process" name="Customer" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_5DIjcHRrEeKGI7Elg3IrIQ" name="Selenium" username="william.jobs" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_5DJKj3RrEeKGI7Elg3IrIQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_5DJKkHRrEeKGI7Elg3IrIQ" name="Customer">
            <groups xmi:type="actormapping:Groups" xmi:id="_5DJKknRrEeKGI7Elg3IrIQ">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_5DJKlHRrEeKGI7Elg3IrIQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_5DJKk3RrEeKGI7Elg3IrIQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_5DJKkXRrEeKGI7Elg3IrIQ"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_5DJKmnRrEeKGI7Elg3IrIQ" type="CONNECTOR" definitionId="MiniStockCheck" definitionVersion="1.0" implementationId="MiniStockCheckImpl" implementationVersion="1.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_5DJKm3RrEeKGI7Elg3IrIQ" type="CONNECTOR" definitionId="MiniDueDate" definitionVersion="1.0" implementationId="MiniDueDateImpl" implementationVersion="2.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_5DJKnHRrEeKGI7Elg3IrIQ" type="CONNECTOR" definitionId="email" definitionVersion="1.0.0" implementationId="email-impl" implementationVersion="1.0.0"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKgHRrEeKGI7Elg3IrIQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKgXRrEeKGI7Elg3IrIQ" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_5DJKgnRrEeKGI7Elg3IrIQ" id="MiniStockCheckImpl-1.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_jJ1NgHRuEeKGI7Elg3IrIQ" key="MiniStockCheckImpl -- 1.0" value="MiniStockCheckImpl-1.0" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_5DJKhHRrEeKGI7Elg3IrIQ" id="MiniDueDateImpl-2.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_jKQEQHRuEeKGI7Elg3IrIQ" key="MiniDueDateImpl -- 2.0" value="MiniDueDateImpl-2.0" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_5DJKhnRrEeKGI7Elg3IrIQ" id="email-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_5DJKh3RrEeKGI7Elg3IrIQ" key="email-impl -- 1.0.0" value="bonita-connector-email-impl-1.0.0-SNAPSHOT.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_5DJKiHRrEeKGI7Elg3IrIQ" key="email-impl -- 1.0.0" value="mail-1.4.5.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_5DJKiXRrEeKGI7Elg3IrIQ" key="email-impl -- 1.0.0" value="bonita-commons-test-6.0.Beta.4-SNAPSHOT.jar" exported="false" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_jKriEHRuEeKGI7Elg3IrIQ" key="email-impl -- 1.0.0" value="email-impl-1.0.0" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKi3RrEeKGI7Elg3IrIQ" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKjHRrEeKGI7Elg3IrIQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKjXRrEeKGI7Elg3IrIQ" id="OTHER">
          <fragments xmi:type="configuration:Fragment" xmi:id="_5DJKjnRrEeKGI7Elg3IrIQ" key="joda-time-2.1.jar" value="joda-time-2.1.jar" type="JAR"/>
        </processDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKnXRrEeKGI7Elg3IrIQ" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKnnRrEeKGI7Elg3IrIQ" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKn3RrEeKGI7Elg3IrIQ" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_5DJKoHRrEeKGI7Elg3IrIQ" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_dUp6_savEeWStvAm3pigyA" name="fromAddress" value="mini.buyer@acme.com" typeClassname="java.lang.String" description="From address of email confirming order"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_dUp6_8avEeWStvAm3pigyA" name="authPassword" value="a" typeClassname="java.lang.String" description="Password for email authentication"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_dUp7AMavEeWStvAm3pigyA" name="smtpHost" value="localhost" typeClassname="java.lang.String" description="SMTP host"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_dUp7AcavEeWStvAm3pigyA" name="smtpSecurity" value="false" typeClassname="java.lang.Boolean" description="Use SSL for SMTP"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_dUp7AsavEeWStvAm3pigyA" name="smtpPort" value="2500" typeClassname="java.lang.Integer" description="SMTP port"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_2BL3ii_5EeKnBYGJ1mXUfw" name="fromAddress" value="" typeClassname="java.lang.String" description="From address of email confirming order"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_2BL3iy_5EeKnBYGJ1mXUfw" name="authPassword" value="" typeClassname="java.lang.String" description="Password for email authentication"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_jsfmUDVPEeKBRMXNIgGKDQ" name="smtpHost" value="" typeClassname="java.lang.String" description="SMTP host"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_ydIwIDVPEeKBRMXNIgGKDQ" name="smtpSecurity" value="" typeClassname="java.lang.Boolean" description="Use SSL for SMTP"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_NAthYDWQEeKR_tP1eIB3JQ" name="smtpPort" value="" typeClassname="java.lang.Integer" description="SMTP port"/>
      <contract xmi:type="process:Contract" xmi:id="_ooj7bBvNEeWwB5BI7jdhZw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ePU8DbFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_dUp7EsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dUp7E8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ePU8DrFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_dUp7FMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dUp7FcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ePU8D7FvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_dUp7FsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dUp7F8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ePU8ELFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_dUp7GMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dUp7GcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ePU8EbFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_dUp7GsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dUp7G8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_2BL3jS_5EeKnBYGJ1mXUfw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_2BL3ji_5EeKnBYGJ1mXUfw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_2BL3jy_5EeKnBYGJ1mXUfw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_2BL3kC_5EeKnBYGJ1mXUfw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_2BL3kS_5EeKnBYGJ1mXUfw" name="Double"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_2BL3ki_5EeKnBYGJ1mXUfw" name="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_2BL3ky_5EeKnBYGJ1mXUfw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_2BL3lC_5EeKnBYGJ1mXUfw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_2BL3lS_5EeKnBYGJ1mXUfw" name="XML"/>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3li_5EeKnBYGJ1mXUfw" documentation="Payment options" name="Payment">
      <literals>Mini financial services solution</literals>
      <literals>Full payment at delivery</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3ly_5EeKnBYGJ1mXUfw" documentation="Set of available stripes colors" name="StripesColor">
      <literals>Black</literals>
      <literals>White</literals>
      <literals>None</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3mC_5EeKnBYGJ1mXUfw" documentation="Set of available roof colors" name="RoofColor">
      <literals>White</literals>
      <literals>Black</literals>
      <literals>Body color</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3mS_5EeKnBYGJ1mXUfw" documentation="Mini model type" name="Type">
      <literals>One</literals>
      <literals>Cooper</literals>
      <literals>Cooper S</literals>
      <literals>Cooper JCW</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3mi_5EeKnBYGJ1mXUfw" documentation="Set of available colors" name="Color">
      <literals>Midnight black</literals>
      <literals>British racing green</literals>
      <literals>Pure silver</literals>
      <literals>Chili red</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3my_5EeKnBYGJ1mXUfw" documentation="Car model enumeration" name="Model">
      <literals>Mini Convertible</literals>
      <literals>Mini Hardtop</literals>
      <literals>Mini Clubman</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_2BL3nC_5EeKnBYGJ1mXUfw" documentation="Wheels size" name="Wheels">
      <literals>16' Alloy</literals>
      <literals>17' Alloy</literals>
      <literals>17' Black alloy</literals>
    </datatypes>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_srGByeGOEeOBRccffrPWDw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_2BL3nS_5EeKnBYGJ1mXUfw" type="Process" element="_2BFJsS_5EeKnBYGJ1mXUfw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_2BL3ni_5EeKnBYGJ1mXUfw" type="2007" element="_2BFJsi_5EeKnBYGJ1mXUfw">
      <children xmi:type="notation:DecorationNode" xmi:id="_2BL3ny_5EeKnBYGJ1mXUfw" type="5008" element="_2BFJsi_5EeKnBYGJ1mXUfw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_2BL3oC_5EeKnBYGJ1mXUfw" type="7001" element="_2BFJsi_5EeKnBYGJ1mXUfw">
        <children xmi:type="notation:Node" xmi:id="_dUrJEcavEeWStvAm3pigyA" type="3007" element="_2BFJsy_5EeKnBYGJ1mXUfw">
          <children xmi:type="notation:DecorationNode" xmi:id="_2BL3oi_5EeKnBYGJ1mXUfw" type="5007" element="_2BFJsy_5EeKnBYGJ1mXUfw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_2BL3oy_5EeKnBYGJ1mXUfw" type="7002" element="_2BFJsy_5EeKnBYGJ1mXUfw">
            <children xmi:type="notation:Shape" xmi:id="_2BL3pC_5EeKnBYGJ1mXUfw" type="3005" element="_2BFJtC_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJJMavEeWStvAm3pigyA" type="5005" element="_2BFJtC_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BL3pi_5EeKnBYGJ1mXUfw" x="110" y="152"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BL3py_5EeKnBYGJ1mXUfw" type="3002" element="_2BGX4S_5EeKnBYGJ1mXUfw" fontName="Lucida Grande">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJJsavEeWStvAm3pigyA" type="5024" element="_2BGX4S_5EeKnBYGJ1mXUfw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2BL3qS_5EeKnBYGJ1mXUfw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BL3qi_5EeKnBYGJ1mXUfw" x="40" y="160"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMecC_5EeKnBYGJ1mXUfw" type="3027" element="_2BGX4y_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJKcavEeWStvAm3pigyA" type="5017" element="_2BGX4y_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMeci_5EeKnBYGJ1mXUfw" x="456" y="55" width="75" height="38"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMecy_5EeKnBYGJ1mXUfw" type="3027" element="_2BGX9y_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJK8avEeWStvAm3pigyA" type="5017" element="_2BGX9y_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMedS_5EeKnBYGJ1mXUfw" x="1031" y="152"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMedi_5EeKnBYGJ1mXUfw" type="3062" element="_2BGYBi_5EeKnBYGJ1mXUfw" fontName="Lucida Grande">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJLcavEeWStvAm3pigyA" type="5090" element="_2BGYBi_5EeKnBYGJ1mXUfw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2BMeeC_5EeKnBYGJ1mXUfw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMeeS_5EeKnBYGJ1mXUfw" x="1325" y="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMeei_5EeKnBYGJ1mXUfw" type="3005" element="_2BGYCC_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJMMavEeWStvAm3pigyA" type="5005" element="_2BGYCC_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMefC_5EeKnBYGJ1mXUfw" x="278" y="55" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMefS_5EeKnBYGJ1mXUfw" type="3005" element="_2BHmLC_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJMsavEeWStvAm3pigyA" type="5005" element="_2BHmLC_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMefy_5EeKnBYGJ1mXUfw" x="110" y="55" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMegC_5EeKnBYGJ1mXUfw" type="3005" element="_2BI0WS_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJNMavEeWStvAm3pigyA" type="5005" element="_2BI0WS_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMegi_5EeKnBYGJ1mXUfw" x="642" y="55" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMegy_5EeKnBYGJ1mXUfw" type="3005" element="_2BJbSS_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJNsavEeWStvAm3pigyA" type="5005" element="_2BJbSS_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMehS_5EeKnBYGJ1mXUfw" x="839" y="152" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMehi_5EeKnBYGJ1mXUfw" type="3005" element="_2BJbdi_5EeKnBYGJ1mXUfw" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJOMavEeWStvAm3pigyA" type="5005" element="_2BJbdi_5EeKnBYGJ1mXUfw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMeiC_5EeKnBYGJ1mXUfw" x="1221" y="152" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2BMeiS_5EeKnBYGJ1mXUfw" type="3008" element="_2BKpjy_5EeKnBYGJ1mXUfw" fontName="Lucida Grande">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUrJOsavEeWStvAm3pigyA" type="5026" element="_2BKpjy_5EeKnBYGJ1mXUfw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2BMeiy_5EeKnBYGJ1mXUfw" x="1" y="10"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMejC_5EeKnBYGJ1mXUfw" x="670" y="155" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_2BMejS_5EeKnBYGJ1mXUfw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_2BMeji_5EeKnBYGJ1mXUfw" fontName="Lucida Grande"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_2BMejy_5EeKnBYGJ1mXUfw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_2BMekC_5EeKnBYGJ1mXUfw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMekS_5EeKnBYGJ1mXUfw" x="41" y="10" width="1422" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_2BMeki_5EeKnBYGJ1mXUfw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_2BMeky_5EeKnBYGJ1mXUfw" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_2BMelC_5EeKnBYGJ1mXUfw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_2BMelS_5EeKnBYGJ1mXUfw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2BMeli_5EeKnBYGJ1mXUfw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_2BMely_5EeKnBYGJ1mXUfw"/>
    <edges xmi:type="notation:Connector" xmi:id="_2BMemC_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3Yy_5EeKnBYGJ1mXUfw" source="_2BL3py_5EeKnBYGJ1mXUfw" target="_2BL3pC_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXIMavEeWStvAm3pigyA" type="6001" element="_2BL3Yy_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXIcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXIsavEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BMenC_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BMenS_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3Zi_5EeKnBYGJ1mXUfw" source="_2BMefS_5EeKnBYGJ1mXUfw" target="_2BMeei_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXJMavEeWStvAm3pigyA" type="6001" element="_2BL3Zi_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXJcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXJsavEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BMeoS_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2BMeoi_5EeKnBYGJ1mXUfw" id="(0.07,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BMeoy_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3aS_5EeKnBYGJ1mXUfw" source="_2BMecC_5EeKnBYGJ1mXUfw" target="_2BMegC_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXKcavEeWStvAm3pigyA" type="6001" element="_2BL3aS_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXKsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXK8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BMepy_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BMeqC_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3bC_5EeKnBYGJ1mXUfw" source="_2BMegC_5EeKnBYGJ1mXUfw" target="_2BMeiS_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXLcavEeWStvAm3pigyA" type="6001" element="_2BL3bC_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXLsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXL8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFgC_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFgS_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3by_5EeKnBYGJ1mXUfw" source="_2BL3pC_5EeKnBYGJ1mXUfw" target="_2BMefS_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXMcavEeWStvAm3pigyA" type="6001" element="_2BL3by_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXMsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXM8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFhS_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2BNFhi_5EeKnBYGJ1mXUfw" id="(0.45,0.96)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFhy_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3ci_5EeKnBYGJ1mXUfw" source="_2BMeei_5EeKnBYGJ1mXUfw" target="_2BMecC_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXNsavEeWStvAm3pigyA" type="6001" element="_2BL3ci_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXN8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXOMavEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFiy_5EeKnBYGJ1mXUfw" points="[0, 0, -115, 82]$[65, -73, -50, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2BNFjC_5EeKnBYGJ1mXUfw" id="(1.0,0.42)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFjS_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3dS_5EeKnBYGJ1mXUfw" source="_2BMeiS_5EeKnBYGJ1mXUfw" target="_2BL3pC_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXO8avEeWStvAm3pigyA" type="6001" element="_2BL3dS_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXPMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXPcavEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFkS_5EeKnBYGJ1mXUfw" points="[-43, -7, 529, -1]$[-574, -31, -2, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2BNFki_5EeKnBYGJ1mXUfw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFky_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3ei_5EeKnBYGJ1mXUfw" source="_2BMeiS_5EeKnBYGJ1mXUfw" target="_2BMegy_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXQMavEeWStvAm3pigyA" type="6001" element="_2BL3ei_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXQcavEeWStvAm3pigyA" y="12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXQsavEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFly_5EeKnBYGJ1mXUfw" points="[21, 1, 18, -111]$[21, 109, 18, -3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2BNFmC_5EeKnBYGJ1mXUfw" id="(0.03,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFmS_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3gS_5EeKnBYGJ1mXUfw" source="_2BMegy_5EeKnBYGJ1mXUfw" target="_2BMecy_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXRcavEeWStvAm3pigyA" type="6001" element="_2BL3gS_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXRsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXR8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFnS_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFni_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3hC_5EeKnBYGJ1mXUfw" source="_2BMecy_5EeKnBYGJ1mXUfw" target="_2BMehi_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXScavEeWStvAm3pigyA" type="6001" element="_2BL3hC_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXSsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXS8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFoi_5EeKnBYGJ1mXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2BNFoy_5EeKnBYGJ1mXUfw" type="4001" element="_2BL3hy_5EeKnBYGJ1mXUfw" source="_2BMehi_5EeKnBYGJ1mXUfw" target="_2BMedi_5EeKnBYGJ1mXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dUsXTcavEeWStvAm3pigyA" type="6001" element="_2BL3hy_5EeKnBYGJ1mXUfw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dUsXTsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dUsXT8avEeWStvAm3pigyA" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2BNFpy_5EeKnBYGJ1mXUfw" points="[6, -25, -69, 52]$[6, -78, -69, -1]$[60, -78, -15, -1]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
