<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Q2uUMbvYEeKuuMrgmiHc2w" name="ProcessVariablesDiagram" author="truc" bonitaVersion="7.4.0" bonitaModelVersion="7.2.0-002" configId="ACED000574002750726F636573735661726961626C65734469616772616D372E322E302D303032372E342E307370">
    <elements xmi:type="process:Pool" xmi:id="_RWA4QLvYEeKuuMrgmiHc2w" documentation="This process aims at testing all types of variable (especially updating variable values within Portal aka &quot;case variables&quot;)." name="ProcessVariablesPool" welcomePageInternal="false" basedOnLookAndFeel="Default Application" entryPageFlowType="SKIP">
      <elements xmi:type="process:Lane" xmi:id="_RkBfELvYEeKuuMrgmiHc2w" name="Employee lane" actor="_Rj6KULvYEeKuuMrgmiHc2w">
        <elements xmi:type="process:Task" xmi:id="_RlnagLvYEeKuuMrgmiHc2w" name="Review variables initial value" outgoing="_Zyq0ILvbEeKuuMrgmiHc2w _aOUOULvbEeKuuMrgmiHc2w _is8AcLvbEeKuuMrgmiHc2w _kQbMcLvbEeKuuMrgmiHc2w _l2jcwLvbEeKuuMrgmiHc2w _mxvSoLvbEeKuuMrgmiHc2w _oJZpILvbEeKuuMrgmiHc2w _o7sBsLvbEeKuuMrgmiHc2w _pqxVQLvbEeKuuMrgmiHc2w _6OjQoLvbEeKuuMrgmiHc2w" incoming="_RyW2ALvYEeKuuMrgmiHc2w" useCardinality="true" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Rl5uYLvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Rl5HUbvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Rl5HULvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Rl5HUrvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Rl5uYbvYEeKuuMrgmiHc2w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Rl5uYrvYEeKuuMrgmiHc2w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bv8COjpTEeSntPZ4lnT8Jg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bv8COzpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bv8CPDpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_rHhZILx1EeKbXMZfvCXhdQ" name="Review_variables_initial_value" nColumn="2" nLine="5">
            <widgets xmi:type="form:TextFormField" xmi:id="_rHhZIbx1EeKbXMZfvCXhdQ" name="varLong" labelPosition="Left" returnTypeModifier="java.lang.Long">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_rHhZIrx1EeKbXMZfvCXhdQ" line="2"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfHcavEeWStvAm3pigyA" name="varLong" content="varLong" type="TYPE_VARIABLE" returnType="java.lang.Long">
                <referencedElements xmi:type="process:Data" xmi:id="_uKvPyOGOEeOBRccffrPWDw" name="varLong" dataType="_Q2uUNbvYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfH8avEeWStvAm3pigyA" name="Long:" content="Long:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfIMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_rHhZJrx1EeKbXMZfvCXhdQ">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfPcavEeWStvAm3pigyA" name="varLong" content="varLong" type="TYPE_VARIABLE" returnType="java.lang.Long">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfPsavEeWStvAm3pigyA" name="varLong" dataType="_Q2uUNbvYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfP8avEeWStvAm3pigyA" name="field_varLong" content="field_varLong" type="TYPE_INPUT" returnType="java.lang.Long">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_d2tfQMavEeWStvAm3pigyA" name="varLong" returnTypeModifier="java.lang.Long"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_rHhZKrx1EeKbXMZfvCXhdQ" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:RadioFormField" xmi:id="_rHhZNbx1EeKbXMZfvCXhdQ" name="varOption" labelPosition="Left">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfUcavEeWStvAm3pigyA" column="1" verticalSpan="3"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfUsavEeWStvAm3pigyA" name="ColorList values" content="[&quot;White&quot;,&quot;Yellow&quot;,&quot;Green&quot;,&quot;Blue&quot;,&quot;Red&quot;,&quot;Black&quot;]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfU8avEeWStvAm3pigyA" name="Option:" content="Option:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfVMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d2tfVcavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfVsavEeWStvAm3pigyA" name="varOption" content="varOption" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfV8avEeWStvAm3pigyA" name="varOption" dataType="_1RJp4LvYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfWMavEeWStvAm3pigyA" name="field_varOption" content="field_varOption" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:RadioFormField" xmi:id="_uKv2mOGOEeOBRccffrPWDw" name="varOption"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d2tfWsavEeWStvAm3pigyA" type="ASSIGNMENT"/>
              </action>
              <defaultExpression xmi:type="expression:Expression" xmi:id="_d2tfW8avEeWStvAm3pigyA" name="varOption" content="varOption" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_d2tfXMavEeWStvAm3pigyA" name="varOption" dataType="_1RJp4LvYEeKuuMrgmiHc2w"/>
              </defaultExpression>
            </widgets>
            <widgets xmi:type="form:DateFormField" xmi:id="_rHiANbx1EeKbXMZfvCXhdQ" name="varDate" labelPosition="Left">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfXcavEeWStvAm3pigyA" line="4"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfXsavEeWStvAm3pigyA" name="varDate" content="varDate" type="TYPE_VARIABLE" returnType="java.util.Date">
                <referencedElements xmi:type="process:Data" xmi:id="_d2tfX8avEeWStvAm3pigyA" name="varDate" dataType="_Q2uUM7vYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfYMavEeWStvAm3pigyA" name="Date:" content="Date:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfYcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d2tfYsavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfY8avEeWStvAm3pigyA" name="varDate" content="varDate" type="TYPE_VARIABLE" returnType="java.util.Date">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfZMavEeWStvAm3pigyA" name="varDate" dataType="_Q2uUM7vYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfZcavEeWStvAm3pigyA" name="field_varDate" content="field_varDate" type="TYPE_INPUT" returnType="java.util.Date">
                  <referencedElements xmi:type="form:DateFormField" xmi:id="_uKv2peGOEeOBRccffrPWDw" name="varDate"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d2tfZ8avEeWStvAm3pigyA" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_rHiASbx1EeKbXMZfvCXhdQ" name="varDouble" labelPosition="Left" returnTypeModifier="java.lang.Double">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_rHiASrx1EeKbXMZfvCXhdQ" line="3"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfI8avEeWStvAm3pigyA" name="varDouble" content="varDouble" type="TYPE_VARIABLE" returnType="java.lang.Double">
                <referencedElements xmi:type="process:Data" xmi:id="_uKvPzuGOEeOBRccffrPWDw" name="varDouble" dataType="_Q2uUNrvYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfJcavEeWStvAm3pigyA" name="Double:" content="Double:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfJsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_rHiATrx1EeKbXMZfvCXhdQ">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfQsavEeWStvAm3pigyA" name="varDouble" content="varDouble" type="TYPE_VARIABLE" returnType="java.lang.Double">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfQ8avEeWStvAm3pigyA" name="varDouble" dataType="_Q2uUNrvYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfRMavEeWStvAm3pigyA" name="field_varDouble" content="field_varDouble" type="TYPE_INPUT" returnType="java.lang.Double">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_d2tfRcavEeWStvAm3pigyA" name="varDouble" returnTypeModifier="java.lang.Double"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_rHiAUrx1EeKbXMZfvCXhdQ" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_rHiAXbx1EeKbXMZfvCXhdQ" name="varBoolean" labelPosition="Left">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfaMavEeWStvAm3pigyA" line="3" column="1"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfacavEeWStvAm3pigyA" name="varBoolean" content="varBoolean" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_d2tfasavEeWStvAm3pigyA" name="varBoolean" dataType="_Q2uUMrvYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfa8avEeWStvAm3pigyA" name="Boolean:" content="Boolean:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfbMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d2tfbcavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfbsavEeWStvAm3pigyA" name="varBoolean" content="varBoolean" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfb8avEeWStvAm3pigyA" name="varBoolean" dataType="_Q2uUMrvYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfcMavEeWStvAm3pigyA" name="field_varBoolean" content="field_varBoolean" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_uKv2sOGOEeOBRccffrPWDw" name="varBoolean"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d2tfcsavEeWStvAm3pigyA" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_rHinSbx1EeKbXMZfvCXhdQ" name="varText" labelPosition="Left">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_rHinSrx1EeKbXMZfvCXhdQ"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfKcavEeWStvAm3pigyA" name="varText" content="varText" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_uKvP1OGOEeOBRccffrPWDw" name="varText" dataType="_Q2uUN7vYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfK8avEeWStvAm3pigyA" name="Text:" content="Text:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfLMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_rHinTrx1EeKbXMZfvCXhdQ">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfR8avEeWStvAm3pigyA" name="varText" content="varText" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfSMavEeWStvAm3pigyA" name="varText" dataType="_Q2uUN7vYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfScavEeWStvAm3pigyA" name="field_varText" content="field_varText" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_d2tfSsavEeWStvAm3pigyA" name="varText"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_rHinUrx1EeKbXMZfvCXhdQ" type="ASSIGNMENT"/>
              </action>
              <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_d2tfLsavEeWStvAm3pigyA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_d2tfL8avEeWStvAm3pigyA" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_rHinXbx1EeKbXMZfvCXhdQ" name="varInteger" labelPosition="Left" returnTypeModifier="java.lang.Integer">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_rHinXrx1EeKbXMZfvCXhdQ" line="1"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfMcavEeWStvAm3pigyA" name="varInteger" content="varInteger" type="TYPE_VARIABLE" returnType="java.lang.Integer">
                <referencedElements xmi:type="process:Data" xmi:id="_uKvP3OGOEeOBRccffrPWDw" name="varInteger" dataType="_Q2uUNLvYEeKuuMrgmiHc2w"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfM8avEeWStvAm3pigyA" name="Integer:" content="Integer:" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfNMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_rHinYrx1EeKbXMZfvCXhdQ">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfTMavEeWStvAm3pigyA" name="varInteger" content="varInteger" type="TYPE_VARIABLE" returnType="java.lang.Integer">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tfTcavEeWStvAm3pigyA" name="varInteger" dataType="_Q2uUNLvYEeKuuMrgmiHc2w"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfTsavEeWStvAm3pigyA" name="field_varInteger" content="field_varInteger" type="TYPE_INPUT" returnType="java.lang.Integer">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="_d2tfT8avEeWStvAm3pigyA" name="varInteger" returnTypeModifier="java.lang.Integer"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_rHinZrx1EeKbXMZfvCXhdQ" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_rHincbx1EeKbXMZfvCXhdQ" name="Submit1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfc8avEeWStvAm3pigyA" line="4" column="1"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfdMavEeWStvAm3pigyA" name="Submit" content="Submit" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfdcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_d2tfGMavEeWStvAm3pigyA" name="Review variables initial value" content="Review variables initial value" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_jMmb4LxzEeKbXMZfvCXhdQ" content=""/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pjpDfBvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d2tfecavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pjpDexvNEeWwB5BI7jdhZw"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_RvwN8LvYEeKuuMrgmiHc2w" name="Start1" outgoing="_RyW2ALvYEeKuuMrgmiHc2w">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfgMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfgcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfgsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfg8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6huEQLvbEeKuuMrgmiHc2w" name="Terminate" outgoing="_7_Dk8LvbEeKuuMrgmiHc2w" incoming="_6OjQoLvbEeKuuMrgmiHc2w" useCardinality="true" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_9yZx4LvbEeKuuMrgmiHc2w" source="_9xsnQLvbEeKuuMrgmiHc2w"/>
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_6OPuo7vbEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6OPuobvbEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6OPuoLvbEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6OPuorvbEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6OPupLvbEeKuuMrgmiHc2w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6OPupbvbEeKuuMrgmiHc2w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bv8CRjpTEeSntPZ4lnT8Jg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bv8CRzpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bv8CSDpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_0LeX0LxzEeKbXMZfvCXhdQ" name="Terminate" nLine="2">
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_0Le-4LxzEeKbXMZfvCXhdQ" name="Submit1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfdsavEeWStvAm3pigyA" line="1"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfd8avEeWStvAm3pigyA" name="Submit" content="Submit" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfeMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </widgets>
            <widgets xmi:type="form:MessageInfo" xmi:id="_0xbkkLxzEeKbXMZfvCXhdQ" name="Message1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d2tfhMavEeWStvAm3pigyA"/>
              <displayDependentWidgetOnlyAfterFirstEventTriggeredAndCondition xmi:type="expression:Expression" xmi:id="_d2tfhcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <displayAfterEventDependsOnConditionScript xmi:type="expression:Expression" xmi:id="_d2tfhsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d2tfh8avEeWStvAm3pigyA" name="A shortcut to terminate the process instance" content="A shortcut to terminate the process instance"/>
              <afterEventExpression xmi:type="expression:Expression" xmi:id="_d2tfiMavEeWStvAm3pigyA" name="" content=""/>
              <tooltip xmi:type="expression:Expression" xmi:id="_d2tficavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <helpMessage xmi:type="expression:Expression" xmi:id="_d2tfisavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d2tfi8avEeWStvAm3pigyA" name="Message1" content="Message1" returnTypeFixed="true"/>
              <injectWidgetScript xmi:type="expression:Expression" xmi:id="_d2tfjMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d2tfjcavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d2tfjsavEeWStvAm3pigyA"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d2tfj8avEeWStvAm3pigyA"/>
                <operator xmi:type="expression:Operator" xmi:id="_d2tfkMavEeWStvAm3pigyA" type="ASSIGNMENT" expression="="/>
              </action>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_d2tfG8avEeWStvAm3pigyA" name="Terminate" content="Terminate" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_yZ_zILxzEeKbXMZfvCXhdQ" content=""/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pjpDihvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d2tfesavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pjpDiRvNEeWwB5BI7jdhZw"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_7--FYLvbEeKuuMrgmiHc2w" name="Terminate end event1" incoming="_7_Dk8LvbEeKuuMrgmiHc2w">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfkcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfksavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfk8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tflMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_9xsnQLvbEeKuuMrgmiHc2w" text="This is to terminate the process without any check."/>
        <elements xmi:type="process:ServiceTask" xmi:id="_kWmeMLvhEeKuuMrgmiHc2w" name="Text" outgoing="_KVAnwLvlEeKt5eaZSPjquw" incoming="_Zyq0ILvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfmcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfmsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfm8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfnMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_vD0TwbxuEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_vD060LxuEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_vD060bxuEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgBcavEeWStvAm3pigyA" name="var" content="varText" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgBsavEeWStvAm3pigyA" name="varText" dataType="_Q2uUN7vYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tfnsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tfn8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tfoMavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tfocavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tfosavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_klsqILvhEeKuuMrgmiHc2w" name="Boolean" outgoing="_Tpzz8LvlEeKt5eaZSPjquw" incoming="_aOUOULvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfo8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfpMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfpcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfpsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_9DvyULxuEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_9DvyUbxuEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_9DvyUrxuEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgB8avEeWStvAm3pigyA" name="var" content="varBoolean" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgCMavEeWStvAm3pigyA" name="varBoolean" dataType="_Q2uUMrvYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tfqMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tfqcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tfqsavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tfq8avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tfrMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_k1CGoLvhEeKuuMrgmiHc2w" name="Date" outgoing="_U_ueALvlEeKt5eaZSPjquw" incoming="_is8AcLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfrcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfrsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfr8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfsMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="__sqVULxuEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="__sqVUbxuEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="__sqVUrxuEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgCcavEeWStvAm3pigyA" name="var" content="varDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgCsavEeWStvAm3pigyA" name="varDate" dataType="_Q2uUM7vYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tfssavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tfs8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tftMavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tftcavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tftsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lGb_sLvhEeKuuMrgmiHc2w" name="Integer" outgoing="_WEJvcLvlEeKt5eaZSPjquw" incoming="_kQbMcLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tft8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfuMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfucavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfusavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_CNLxULxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_CNLxUbxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_CNLxUrxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgC8avEeWStvAm3pigyA" name="var" content="varInteger" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgDMavEeWStvAm3pigyA" name="varInteger" dataType="_Q2uUNLvYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tfvMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tfvcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tfvsavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tfv8avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tfwMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ld4PULvhEeKuuMrgmiHc2w" name="Long" outgoing="_XCQWcLvlEeKt5eaZSPjquw" incoming="_l2jcwLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfwcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfwsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfw8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfxMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_FOTY8LxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_FOTY8bxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_FOTY8rxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgDcavEeWStvAm3pigyA" name="var" content="varLong" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgDsavEeWStvAm3pigyA" name="varLong" dataType="_Q2uUNbvYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tfxsavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tfx8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tfyMavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tfycavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tfysavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_lvyesLvhEeKuuMrgmiHc2w" name="Double" outgoing="_MFu-gLvlEeKt5eaZSPjquw" incoming="_mxvSoLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tfy8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tfzMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfzcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfzsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_G-qjULxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_G-qjUbxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G-qjUrxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgD8avEeWStvAm3pigyA" name="var" content="varDouble" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgEMavEeWStvAm3pigyA" name="varDouble" dataType="_Q2uUNrvYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tf0MavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tf0cavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tf0savEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tf08avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tf1MavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_l_WksLvhEeKuuMrgmiHc2w" name="Option" outgoing="_NyEkgLvlEeKt5eaZSPjquw" incoming="_oJZpILvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tf1cavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tf1savEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tf18avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tf2MavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_IxDG8LxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_IxDG8bxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_IxDG8rxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgEcavEeWStvAm3pigyA" name="var" content="varOption" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_d2tgEsavEeWStvAm3pigyA" name="varOption" dataType="_1RJp4LvYEeKuuMrgmiHc2w"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tf2savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tf28avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tf3MavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tf3cavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tf3savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mQafgLvhEeKuuMrgmiHc2w" name="Java Object" outgoing="_PUojcLvlEeKt5eaZSPjquw" incoming="_o7sBsLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tf38avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tf4MavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tf4cavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tf4savEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_K5uqsLxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_K5uqsbxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_K5uqsrxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgE8avEeWStvAm3pigyA" name="var" content="varJavaObject" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_uKv3Q-GOEeOBRccffrPWDw" name="varJavaObject" dataType="_Q2uUOLvYEeKuuMrgmiHc2w" className="java.sql.ResultSet"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tf5MavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tf5cavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tf5savEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tf58avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tf6MavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mgsXMLvhEeKuuMrgmiHc2w" name="XML" outgoing="_QvlegLvlEeKt5eaZSPjquw" incoming="_pqxVQLvbEeKuuMrgmiHc2w" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tf6cavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tf6savEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tf68avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tf7MavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Mzr18LxvEeKbXMZfvCXhdQ" name="check_variable" definitionId="check-variable" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Mzr18bxvEeKbXMZfvCXhdQ" definitionId="check-variable" version="1.0.0" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Mzr18rxvEeKbXMZfvCXhdQ" key="inputVariable">
                <expression xmi:type="expression:Expression" xmi:id="_d2tgFcavEeWStvAm3pigyA" name="var" content="varXML" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true">
                  <referencedElements xmi:type="process:XMLData" xmi:id="_uKv3ReGOEeOBRccffrPWDw" name="varXML" dataType="_Q2uUObvYEeKuuMrgmiHc2w" namespace="http://www.example.org/GolfCountryClub" type="GolfCountryClub"/>
                </expression>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d2tf7savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d2tf78avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d2tf8MavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d2tf8cavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d2tf8savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_bqErkLvkEeKt5eaZSPjquw" name="Last human step" outgoing="_fWc2sLvkEeKt5eaZSPjquw" incoming="_SZ8HgLvlEeKt5eaZSPjquw" useCardinality="true" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ZGD2srvkEeKt5eaZSPjquw" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZGD2sLvkEeKt5eaZSPjquw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZGDPoLvkEeKt5eaZSPjquw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZGD2sbvkEeKt5eaZSPjquw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZGD2s7vkEeKt5eaZSPjquw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZGD2tLvkEeKt5eaZSPjquw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bv8CUDpTEeSntPZ4lnT8Jg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bv8CUTpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bv8CUjpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_bz25sLvkEeKt5eaZSPjquw" content=""/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pjpDlhvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d2tfe8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pjpDlRvNEeWwB5BI7jdhZw"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_fWFDQLvkEeKt5eaZSPjquw" name="Terminate end event2" incoming="_fWc2sLvkEeKt5eaZSPjquw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tflcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tflsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tfl8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tfmMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_JXtSALvlEeKt5eaZSPjquw" name="Gateway1" outgoing="_SZ8HgLvlEeKt5eaZSPjquw" incoming="_KVAnwLvlEeKt5eaZSPjquw _MFu-gLvlEeKt5eaZSPjquw _NyEkgLvlEeKt5eaZSPjquw _PUojcLvlEeKt5eaZSPjquw _QvlegLvlEeKt5eaZSPjquw _Tpzz8LvlEeKt5eaZSPjquw _U_ueALvlEeKt5eaZSPjquw _WEJvcLvlEeKt5eaZSPjquw _XCQWcLvlEeKt5eaZSPjquw">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d2tgGcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d2tgGsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d2tgG8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d2tgHMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_SEa2YLvYEeKuuMrgmiHc2w" path="_RWA4QLvYEeKuuMrgmiHc2w/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_RWQv4LvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_RWQI17vYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_SEa2YbvYEeKuuMrgmiHc2w" path="_RWA4QLvYEeKuuMrgmiHc2w/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_SEa2Y7vYEeKuuMrgmiHc2w" path="_RWA4QLvYEeKuuMrgmiHc2w/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_SEa2YrvYEeKuuMrgmiHc2w" path="_RWA4QLvYEeKuuMrgmiHc2w/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_kY-y4LvYEeKuuMrgmiHc2w" name="varText" dataType="_Q2uUN7vYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfNsavEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_lRtxsLvYEeKuuMrgmiHc2w" name="varBoolean" dataType="_Q2uUMrvYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfN8avEeWStvAm3pigyA" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_o3HyILvYEeKuuMrgmiHc2w" name="varDate" dataType="_Q2uUM7vYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfOMavEeWStvAm3pigyA" name="" content="" interpreter="GROOVY" returnType="java.util.Date" returnTypeFixed="true"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_p0jDsLvYEeKuuMrgmiHc2w" name="varInteger" dataType="_Q2uUNLvYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfOcavEeWStvAm3pigyA" content="" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_qjOuoLvYEeKuuMrgmiHc2w" name="varLong" dataType="_Q2uUNbvYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfOsavEeWStvAm3pigyA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_rdc7MLvYEeKuuMrgmiHc2w" name="varDouble" dataType="_Q2uUNrvYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfO8avEeWStvAm3pigyA" content="" returnType="java.lang.Double"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2Gq8oLvYEeKuuMrgmiHc2w" name="varOption" dataType="_1RJp4LvYEeKuuMrgmiHc2w">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tfPMavEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_DdsoILvZEeKuuMrgmiHc2w" name="varJavaObject" dataType="_Q2uUOLvYEeKuuMrgmiHc2w" className="java.sql.ResultSet">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tgF8avEeWStvAm3pigyA" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.sql.ResultSet"/>
      </data>
      <data xmi:type="process:XMLData" xmi:id="_V5ktkLvZEeKuuMrgmiHc2w" name="varXML" dataType="_Q2uUObvYEeKuuMrgmiHc2w" namespace="http://www.example.org/GolfCountryClub" type="GolfCountryClub">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d2tgGMavEeWStvAm3pigyA" content="" returnType="org.w3c.dom.Document"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_RWQv4rvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_RWQv4bvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_pjocoxvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_d2tffMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_RWQv47vYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_pjocpBvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_d2tffcavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_RWQI1rvYEeKuuMrgmiHc2w" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RyW2ALvYEeKuuMrgmiHc2w" target="_RlnagLvYEeKuuMrgmiHc2w" source="_RvwN8LvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RyW2AbvYEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgHsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Zyq0ILvbEeKuuMrgmiHc2w" target="_kWmeMLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Zyq0IbvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgIMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aOUOULvbEeKuuMrgmiHc2w" target="_klsqILvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aOUOUbvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgIsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_is8AcLvbEeKuuMrgmiHc2w" target="_k1CGoLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_is8ngLvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgJMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kQbMcLvbEeKuuMrgmiHc2w" target="_lGb_sLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kQbzgLvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgJsavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l2jcwLvbEeKuuMrgmiHc2w" target="_ld4PULvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l2jcwbvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgKMavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mxvSoLvbEeKuuMrgmiHc2w" target="_lvyesLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mxvSobvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgKsavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oJZpILvbEeKuuMrgmiHc2w" target="_l_WksLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oJZpIbvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgLMavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_o7sBsLvbEeKuuMrgmiHc2w" target="_mQafgLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_o7sowLvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgLsavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pqxVQLvbEeKuuMrgmiHc2w" target="_mgsXMLvhEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pqx8ULvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgMMavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6OjQoLvbEeKuuMrgmiHc2w" target="_6huEQLvbEeKuuMrgmiHc2w" source="_RlnagLvYEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6OjQobvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgMsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7_Dk8LvbEeKuuMrgmiHc2w" target="_7--FYLvbEeKuuMrgmiHc2w" source="_6huEQLvbEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7_Dk8bvbEeKuuMrgmiHc2w"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgNMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fWc2sLvkEeKt5eaZSPjquw" target="_fWFDQLvkEeKt5eaZSPjquw" source="_bqErkLvkEeKt5eaZSPjquw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fWc2sbvkEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgNsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KVAnwLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_kWmeMLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KVAnwbvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgOMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MFu-gLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_lvyesLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MFvlkLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgOsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NyEkgLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_l_WksLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NyFLkLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgPMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PUojcLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_mQafgLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PUpKgLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgPsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QvlegLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_mgsXMLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QvlegbvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgQMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SZ8HgLvlEeKt5eaZSPjquw" target="_bqErkLvkEeKt5eaZSPjquw" source="_JXtSALvlEeKt5eaZSPjquw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SZ8ukLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgQsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Tpzz8LvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_klsqILvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Tp3eULvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgRMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_U_ueALvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_k1CGoLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_U_vFELvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgRsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WEJvcLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_lGb_sLvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WEKWgLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgSMavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XCQWcLvlEeKt5eaZSPjquw" target="_JXtSALvlEeKt5eaZSPjquw" source="_ld4PULvhEeKuuMrgmiHc2w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XCQ9gLvlEeKt5eaZSPjquw"/>
        <condition xmi:type="expression:Expression" xmi:id="_d2tgSsavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Rj6KULvYEeKuuMrgmiHc2w" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_wfifkLvZEeKuuMrgmiHc2w" name="Selenium" version="6.0.0-ga-003" username="william.jobs" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_wfiflrvZEeKuuMrgmiHc2w">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_wfifl7vZEeKuuMrgmiHc2w" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_wfifmbvZEeKuuMrgmiHc2w">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_wfifm7vZEeKuuMrgmiHc2w"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_wfifmrvZEeKuuMrgmiHc2w"/>
            <users xmi:type="actormapping:Users" xmi:id="_wfifmLvZEeKuuMrgmiHc2w"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_Esx7ULviEeKuuMrgmiHc2w" type="CONNECTOR" definitionId="check-variable" definitionVersion="1.0.0" implementationId="check-variable-impl" implementationVersion="1.0.0"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifkbvZEeKuuMrgmiHc2w" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifkrvZEeKuuMrgmiHc2w" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_EtcCoLviEeKuuMrgmiHc2w" id="check-variable-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_HD2hILx2EeKbXMZfvCXhdQ" key="check-variable-impl -- 1.0.0" value="check-variable-impl-1.0.0" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifk7vZEeKuuMrgmiHc2w" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfiflLvZEeKuuMrgmiHc2w" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfiflbvZEeKuuMrgmiHc2w" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifnLvZEeKuuMrgmiHc2w" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifnbvZEeKuuMrgmiHc2w" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifnrvZEeKuuMrgmiHc2w" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_wfifn7vZEeKuuMrgmiHc2w" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_pjocpRvNEeWwB5BI7jdhZw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RWPhwLvYEeKuuMrgmiHc2w">
        <name xmi:type="expression:Expression" xmi:id="_d2tgXcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d2tgXsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RWPhw7vYEeKuuMrgmiHc2w">
        <name xmi:type="expression:Expression" xmi:id="_d2tgX8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d2tgYMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RWPhxrvYEeKuuMrgmiHc2w">
        <name xmi:type="expression:Expression" xmi:id="_d2tgYcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d2tgYsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RWQI0LvYEeKuuMrgmiHc2w">
        <name xmi:type="expression:Expression" xmi:id="_d2tgY8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d2tgZMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_RWQI07vYEeKuuMrgmiHc2w">
        <name xmi:type="expression:Expression" xmi:id="_d2tgZcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d2tgZsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <formMapping xmi:type="process:FormMapping" xmi:id="_pjocbxvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_d2tffsavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </formMapping>
    <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_pjoccBvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_d2tff8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </overviewFormMapping>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Q2uUMrvYEeKuuMrgmiHc2w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Q2uUM7vYEeKuuMrgmiHc2w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Q2uUNLvYEeKuuMrgmiHc2w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Q2uUNbvYEeKuuMrgmiHc2w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Q2uUNrvYEeKuuMrgmiHc2w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Q2uUN7vYEeKuuMrgmiHc2w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Q2uUOLvYEeKuuMrgmiHc2w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Q2uUObvYEeKuuMrgmiHc2w" name="XML"/>
    <datatypes xmi:type="process:EnumType" xmi:id="_1RJp4LvYEeKuuMrgmiHc2w" documentation="Some colors" name="ColorList">
      <literals>White</literals>
      <literals>Yellow</literals>
      <literals>Green</literals>
      <literals>Blue</literals>
      <literals>Red</literals>
      <literals>Black</literals>
    </datatypes>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_uKuofuGOEeOBRccffrPWDw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Q2u7QLvYEeKuuMrgmiHc2w" type="Process" element="_Q2uUMbvYEeKuuMrgmiHc2w" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_RZfqELvYEeKuuMrgmiHc2w" type="2007" element="_RWA4QLvYEeKuuMrgmiHc2w">
      <children xmi:type="notation:DecorationNode" xmi:id="_RZg4MLvYEeKuuMrgmiHc2w" type="5008" element="_RWA4QLvYEeKuuMrgmiHc2w"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_RZg4MbvYEeKuuMrgmiHc2w" type="7001" element="_RWA4QLvYEeKuuMrgmiHc2w">
        <children xmi:type="notation:Node" xmi:id="_d2tgkcavEeWStvAm3pigyA" type="3007" element="_RkBfELvYEeKuuMrgmiHc2w">
          <children xmi:type="notation:DecorationNode" xmi:id="_RkPhhbvYEeKuuMrgmiHc2w" type="5007" element="_RkBfELvYEeKuuMrgmiHc2w"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_RkQIkLvYEeKuuMrgmiHc2w" type="7002" element="_RkBfELvYEeKuuMrgmiHc2w">
            <children xmi:type="notation:Shape" xmi:id="_RmNQYLvYEeKuuMrgmiHc2w" type="3005" element="_RlnagLvYEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGIMavEeWStvAm3pigyA" type="5005" element="_RlnagLvYEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RmNQYbvYEeKuuMrgmiHc2w" x="138" y="23" width="192" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Rv5-8LvYEeKuuMrgmiHc2w" type="3002" element="_RvwN8LvYEeKuuMrgmiHc2w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGIsavEeWStvAm3pigyA" type="5024" element="_RvwN8LvYEeKuuMrgmiHc2w">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Rv6mAbvYEeKuuMrgmiHc2w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Rv5-8bvYEeKuuMrgmiHc2w" x="49" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6hv5cLvbEeKuuMrgmiHc2w" type="3005" element="_6huEQLvbEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGJcavEeWStvAm3pigyA" type="5005" element="_6huEQLvbEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6hv5cbvbEeKuuMrgmiHc2w" x="974" y="46" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7-_TgLvbEeKuuMrgmiHc2w" type="3062" element="_7--FYLvbEeKuuMrgmiHc2w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGJ8avEeWStvAm3pigyA" type="5090" element="_7--FYLvbEeKuuMrgmiHc2w">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7-_Tg7vbEeKuuMrgmiHc2w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7-_TgbvbEeKuuMrgmiHc2w" x="1164" y="56"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_d2tgncavEeWStvAm3pigyA" type="3015" element="_9xsnQLvbEeKuuMrgmiHc2w">
              <children xmi:type="notation:DecorationNode" xmi:id="_9xz8ALvbEeKuuMrgmiHc2w" type="5010" element="_9xsnQLvbEeKuuMrgmiHc2w"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_9xyt4bvbEeKuuMrgmiHc2w"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_9xyt4rvbEeKuuMrgmiHc2w" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_9xyt47vbEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9xyt5LvbEeKuuMrgmiHc2w" x="974" y="122" width="190"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kWr9wLvhEeKuuMrgmiHc2w" type="3027" element="_kWmeMLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGKsavEeWStvAm3pigyA" type="5017" element="_kWmeMLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kWr9wbvhEeKuuMrgmiHc2w" x="62" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_klvGYLvhEeKuuMrgmiHc2w" type="3027" element="_klsqILvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGLMavEeWStvAm3pigyA" type="5017" element="_klsqILvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_klvGYbvhEeKuuMrgmiHc2w" x="214" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_k1D70LvhEeKuuMrgmiHc2w" type="3027" element="_k1CGoLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGLsavEeWStvAm3pigyA" type="5017" element="_k1CGoLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k1D70bvhEeKuuMrgmiHc2w" x="366" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lGd04LvhEeKuuMrgmiHc2w" type="3027" element="_lGb_sLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGMMavEeWStvAm3pigyA" type="5017" element="_lGb_sLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lGd04bvhEeKuuMrgmiHc2w" x="518" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ld6EgLvhEeKuuMrgmiHc2w" type="3027" element="_ld4PULvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGMsavEeWStvAm3pigyA" type="5017" element="_ld4PULvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ld6EgbvhEeKuuMrgmiHc2w" x="670" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lv0T4LvhEeKuuMrgmiHc2w" type="3027" element="_lvyesLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGNMavEeWStvAm3pigyA" type="5017" element="_lvyesLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lv0T4bvhEeKuuMrgmiHc2w" x="822" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l_YZ4LvhEeKuuMrgmiHc2w" type="3027" element="_l_WksLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGNsavEeWStvAm3pigyA" type="5017" element="_l_WksLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_YZ4bvhEeKuuMrgmiHc2w" x="974" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mQbGmLvhEeKuuMrgmiHc2w" type="3027" element="_mQafgLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGOMavEeWStvAm3pigyA" type="5017" element="_mQafgLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mQbGmbvhEeKuuMrgmiHc2w" x="1126" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mguMYLvhEeKuuMrgmiHc2w" type="3027" element="_mgsXMLvhEeKuuMrgmiHc2w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGOsavEeWStvAm3pigyA" type="5017" element="_mgsXMLvhEeKuuMrgmiHc2w"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mguMYbvhEeKuuMrgmiHc2w" x="1278" y="312" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bqIV8LvkEeKt5eaZSPjquw" type="3005" element="_bqErkLvkEeKt5eaZSPjquw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGPMavEeWStvAm3pigyA" type="5005" element="_bqErkLvkEeKt5eaZSPjquw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bqIV8bvkEeKt5eaZSPjquw" x="708" y="597" width="139" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fWLJ4LvkEeKt5eaZSPjquw" type="3062" element="_fWFDQLvkEeKt5eaZSPjquw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGPsavEeWStvAm3pigyA" type="5090" element="_fWFDQLvkEeKt5eaZSPjquw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fWLw8bvkEeKt5eaZSPjquw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fWLJ4bvkEeKt5eaZSPjquw" x="936" y="617"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JX1N0LvlEeKt5eaZSPjquw" type="3009" element="_JXtSALvlEeKt5eaZSPjquw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d2uGQcavEeWStvAm3pigyA" type="5020" element="_JXtSALvlEeKt5eaZSPjquw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JX104bvlEeKt5eaZSPjquw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JX1N0bvlEeKt5eaZSPjquw" x="613" y="477"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_RkPhgbvYEeKuuMrgmiHc2w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_RkPhgrvYEeKuuMrgmiHc2w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_RkPhg7vYEeKuuMrgmiHc2w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_RkQIkbvYEeKuuMrgmiHc2w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RkPhhLvYEeKuuMrgmiHc2w" x="22" width="1557" height="702"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_RZfqEbvYEeKuuMrgmiHc2w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_RZfqErvYEeKuuMrgmiHc2w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_RZfqE7vYEeKuuMrgmiHc2w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_RZg4MrvYEeKuuMrgmiHc2w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RZfqFLvYEeKuuMrgmiHc2w"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Q2u7QbvYEeKuuMrgmiHc2w"/>
    <edges xmi:type="notation:Connector" xmi:id="_RyYrMLvYEeKuuMrgmiHc2w" type="4001" element="_RyW2ALvYEeKuuMrgmiHc2w" source="_Rv5-8LvYEeKuuMrgmiHc2w" target="_RmNQYLvYEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGRsavEeWStvAm3pigyA" type="6001" element="_RyW2ALvYEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGR8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGSMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RyYrMrvYEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZyspULvbEeKuuMrgmiHc2w" type="4001" element="_Zyq0ILvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_kWr9wLvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGSsavEeWStvAm3pigyA" type="6001" element="_Zyq0ILvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGS8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGTMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZyspUrvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aOU1YLvbEeKuuMrgmiHc2w" type="4001" element="_aOUOULvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_klvGYLvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGTsavEeWStvAm3pigyA" type="6001" element="_aOUOULvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGT8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGUMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aOU1YrvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_is-csLvbEeKuuMrgmiHc2w" type="4001" element="_is8AcLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_k1D70LvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGUsavEeWStvAm3pigyA" type="6001" element="_is8AcLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGU8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGVMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_is_DwbvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kQdBoLvbEeKuuMrgmiHc2w" type="4001" element="_kQbMcLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_lGd04LvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGVsavEeWStvAm3pigyA" type="6001" element="_kQbMcLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGV8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGWMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kQdBorvbEeKuuMrgmiHc2w" points="[56, 48, -278, -218]$[56, 127, -278, -139]$[302, 127, -32, -139]$[302, 241, -32, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l2kq4LvbEeKuuMrgmiHc2w" type="4001" element="_l2jcwLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_ld6EgLvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGWsavEeWStvAm3pigyA" type="6001" element="_l2jcwLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGW8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGXMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l2kq4rvbEeKuuMrgmiHc2w" points="[87, 48, -399, -218]$[87, 108, -399, -158]$[455, 108, -31, -158]$[455, 241, -31, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mxwgwLvbEeKuuMrgmiHc2w" type="4001" element="_mxvSoLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_lv0T4LvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGXsavEeWStvAm3pigyA" type="6001" element="_mxvSoLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGX8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGYMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mxwgwrvbEeKuuMrgmiHc2w" points="[96, 40, -542, -226]$[322, 40, -316, -226]$[322, 203, -316, -63]$[638, 203, 0, -63]$[638, 241, 0, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oJaQMLvbEeKuuMrgmiHc2w" type="4001" element="_oJZpILvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_l_YZ4LvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGYsavEeWStvAm3pigyA" type="6001" element="_oJZpILvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGY8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGZMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oJaQMrvbEeKuuMrgmiHc2w" points="[96, 32, -694, -234]$[400, 32, -390, -234]$[400, 165, -390, -101]$[790, 165, 0, -101]$[790, 241, 0, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_o7tP0LvbEeKuuMrgmiHc2w" type="4001" element="_o7sBsLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_mQbGmLvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGZsavEeWStvAm3pigyA" type="6001" element="_o7sBsLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGZ8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGaMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_o7tP0rvbEeKuuMrgmiHc2w" points="[96, 27, -846, -239]$[474, 27, -468, -239]$[474, 222, -468, -44]$[942, 222, 0, -44]$[942, 241, 0, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pqyjYLvbEeKuuMrgmiHc2w" type="4001" element="_pqxVQLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_mguMYLvhEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGasavEeWStvAm3pigyA" type="6001" element="_pqxVQLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGa8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGbMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pqyjYrvbEeKuuMrgmiHc2w" points="[96, 23, -998, -243]$[569, 23, -525, -243]$[569, 184, -525, -82]$[1094, 184, 0, -82]$[1094, 241, 0, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6OkewLvbEeKuuMrgmiHc2w" type="4001" element="_6OjQoLvbEeKuuMrgmiHc2w" source="_RmNQYLvYEeKuuMrgmiHc2w" target="_6hv5cLvbEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGbsavEeWStvAm3pigyA" type="6001" element="_6OjQoLvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGb8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGcMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6OkewrvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7_EzELvbEeKuuMrgmiHc2w" type="4001" element="_7_Dk8LvbEeKuuMrgmiHc2w" source="_6hv5cLvbEeKuuMrgmiHc2w" target="_7-_TgLvbEeKuuMrgmiHc2w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGcsavEeWStvAm3pigyA" type="6001" element="_7_Dk8LvbEeKuuMrgmiHc2w">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGc8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGdMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7_EzErvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9ybAALvbEeKuuMrgmiHc2w" type="4003" element="_9yZx4LvbEeKuuMrgmiHc2w" source="_d2tgncavEeWStvAm3pigyA" target="_6hv5cLvbEeKuuMrgmiHc2w">
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGdsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9ybAArvbEeKuuMrgmiHc2w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fWeE0LvkEeKt5eaZSPjquw" type="4001" element="_fWc2sLvkEeKt5eaZSPjquw" source="_bqIV8LvkEeKt5eaZSPjquw" target="_fWLJ4LvkEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGeMavEeWStvAm3pigyA" type="6001" element="_fWc2sLvkEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGecavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGesavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fWeE0rvkEeKt5eaZSPjquw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KVB14LvlEeKt5eaZSPjquw" type="4001" element="_KVAnwLvlEeKt5eaZSPjquw" source="_kWr9wLvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGfMavEeWStvAm3pigyA" type="6001" element="_KVAnwLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGfcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGfsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KVB14rvlEeKt5eaZSPjquw" points="[-50, 21, -515, -177]$[-50, 112, -515, -86]$[455, 112, -10, -86]$[455, 180, -10, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KVDrELvlEeKt5eaZSPjquw" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KVDrEbvlEeKt5eaZSPjquw" id="(0.32558139534883723,0.813953488372093)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MFxawLvlEeKt5eaZSPjquw" type="4001" element="_MFu-gLvlEeKt5eaZSPjquw" source="_lv0T4LvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGgsavEeWStvAm3pigyA" type="6001" element="_MFu-gLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGg8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGhMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MFxawrvlEeKt5eaZSPjquw" points="[-51, 20, 237, -136]$[-51, 141, 237, -15]$[-282, 141, 6, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MF4IcLvlEeKt5eaZSPjquw" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NyHAwLvlEeKt5eaZSPjquw" type="4001" element="_NyEkgLvlEeKt5eaZSPjquw" source="_l_YZ4LvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGh8avEeWStvAm3pigyA" type="6001" element="_NyEkgLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGiMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGicavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NyHAwrvlEeKt5eaZSPjquw" points="[-24, 20, 432, -122]$[-24, 103, 432, -39]$[-423, 103, 33, -39]$[-423, 151, 33, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NyNucLvlEeKt5eaZSPjquw" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NyNucbvlEeKt5eaZSPjquw" id="(0.11627906976744186,0.16279069767441862)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PUq_sLvlEeKt5eaZSPjquw" type="4001" element="_PUojcLvlEeKt5eaZSPjquw" source="_mQbGmLvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGjcavEeWStvAm3pigyA" type="6001" element="_PUojcLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGjsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGj8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PUrmwbvlEeKt5eaZSPjquw" points="[-24, 20, 568, -136]$[-24, 160, 568, 4]$[-574, 160, 18, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PUxtYLvlEeKt5eaZSPjquw" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Qvn6wLvlEeKt5eaZSPjquw" type="4001" element="_QvlegLvlEeKt5eaZSPjquw" source="_mguMYLvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGksavEeWStvAm3pigyA" type="6001" element="_QvlegLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGk8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGlMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Qvn6wrvlEeKt5eaZSPjquw" points="[-50, 23, 694, -136]$[-50, 155, 694, -4]$[-727, 155, 17, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QvuocLvlEeKt5eaZSPjquw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SZ_K0LvlEeKt5eaZSPjquw" type="4001" element="_SZ8HgLvlEeKt5eaZSPjquw" source="_JX1N0LvlEeKt5eaZSPjquw" target="_bqIV8LvkEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGl8avEeWStvAm3pigyA" type="6001" element="_SZ8HgLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGmMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGmcavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SZ_K0rvlEeKt5eaZSPjquw" points="[-22, 15, -143, -111]$[-22, 126, -143, 0]$[52, 126, -69, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SaF4gLvlEeKt5eaZSPjquw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Tp6hoLvlEeKt5eaZSPjquw" type="4001" element="_Tpzz8LvlEeKt5eaZSPjquw" source="_klvGYLvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGnMavEeWStvAm3pigyA" type="6001" element="_Tpzz8LvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGncavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGnsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Tp6horvlEeKt5eaZSPjquw" points="[-50, 22, -370, -246]$[-50, 258, -370, -10]$[309, 258, -11, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TqBPULvlEeKt5eaZSPjquw" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_U_w6QLvlEeKt5eaZSPjquw" type="4001" element="_U_ueALvlEeKt5eaZSPjquw" source="_k1D70LvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGocavEeWStvAm3pigyA" type="6001" element="_U_ueALvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGosavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGo8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_U_w6QrvlEeKt5eaZSPjquw" points="[-62, 23, -230, -163]$[-62, 171, -230, -15]$[162, 171, -6, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_U_3A4LvlEeKt5eaZSPjquw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WEMLsLvlEeKt5eaZSPjquw" type="4001" element="_WEJvcLvlEeKt5eaZSPjquw" source="_lGd04LvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGpsavEeWStvAm3pigyA" type="6001" element="_WEJvcLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGp8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGqMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WEMywLvlEeKt5eaZSPjquw" points="[0, 0, -16, -269]$[24, 255, 8, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WETgcLvlEeKt5eaZSPjquw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XCSysLvlEeKt5eaZSPjquw" type="4001" element="_XCQWcLvlEeKt5eaZSPjquw" source="_ld6EgLvhEeKuuMrgmiHc2w" target="_JX1N0LvlEeKt5eaZSPjquw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGq8avEeWStvAm3pigyA" type="6001" element="_XCQWcLvlEeKt5eaZSPjquw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d2uGrMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d2uGrcavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XCSysrvlEeKt5eaZSPjquw" points="[-51, 21, 85, -163]$[-51, 112, 85, -72]$[-129, 112, 7, -72]$[-129, 169, 7, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XCZgYLvlEeKt5eaZSPjquw" id="(1.0,0.58)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_0LlFgLxzEeKbXMZfvCXhdQ" type="Form" element="_0LeX0LxzEeKbXMZfvCXhdQ" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_0L7DwLxzEeKbXMZfvCXhdQ" type="2126" element="_0Le-4LxzEeKbXMZfvCXhdQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_0L7q0LxzEeKbXMZfvCXhdQ" type="5160" element="_0Le-4LxzEeKbXMZfvCXhdQ"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0L7DwbxzEeKbXMZfvCXhdQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0L7DwrxzEeKbXMZfvCXhdQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0L7Dw7xzEeKbXMZfvCXhdQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0L7DxLxzEeKbXMZfvCXhdQ"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_0yGS8LxzEeKbXMZfvCXhdQ" type="2131" element="_0xbkkLxzEeKbXMZfvCXhdQ" fontName="Segoe UI">
      <children xmi:type="notation:DecorationNode" xmi:id="_d2uGRMavEeWStvAm3pigyA" type="5135" element="_0xbkkLxzEeKbXMZfvCXhdQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0yGS8bxzEeKbXMZfvCXhdQ"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0LlFgbxzEeKbXMZfvCXhdQ"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_rHu0gLx1EeKbXMZfvCXhdQ" type="Form" element="_rHhZILx1EeKbXMZfvCXhdQ" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_rHu0gbx1EeKbXMZfvCXhdQ"/>
  </notation:Diagram>
</xmi:XMI>
