<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_cHMMEIdEEeK7oqVL4jKPeQ" name="ServiceTasksDiagram" author="truc" bonitaVersion="7.7.0" bonitaModelVersion="7.6.0-002" configId="ACED0005740023536572766963655461736B734469616772616D372E362E302D303032372E372E307370">
    <elements xmi:type="process:Pool" xmi:id="_cHqtMIdEEeK7oqVL4jKPeQ" name="ServiceTasksProcess" welcomePageInternal="false" basedOnLookAndFeel="Default Application" entryPageFlowType="SKIP">
      <elements xmi:type="process:Lane" xmi:id="_cI3AAIdEEeK7oqVL4jKPeQ" documentation="This lane is 100% made of service tasks." name="Automated lane" actor="_cIzVoIdEEeK7oqVL4jKPeQ">
        <elements xmi:type="process:ServiceTask" xmi:id="_Pn1S8IdFEeK7oqVL4jKPeQ" documentation="An automated task with connector." name="Service Task 2" outgoing="_CVfeMKNUEeK3qLDNhnWBJg" incoming="_PoLRMIdFEeK7oqVL4jKPeQ" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Pn3IIIdFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pn2hEYdFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Pn2hEIdFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pn2hEodFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_YN9wYIdHEeK7oqVL4jKPeQ" documentation="This is a test groovy script." name="myGroovyScript" definitionId="scripting-groovy" event="ON_FINISH" definitionVersion="1.0.2">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_YN-Xc4dHEeK7oqVL4jKPeQ" definitionId="scripting-groovy" version="1.0.2" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_YN-XdIdHEeK7oqVL4jKPeQ" key="script">
                <expression xmi:type="expression:Expression" xmi:id="_d7JTc8avEeWStvAm3pigyA" name="scriptScript" content="&quot;Hello world!&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_YN9wYYdHEeK7oqVL4jKPeQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_d7JTdMavEeWStvAm3pigyA" name="myMessage" content="myMessage" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="__U4P9QwYEei-AeSrpwoQZQ" documentation="My test message variable." name="myMessage" dataType="_cHMMFodEEeK7oqVL4jKPeQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_d7JTdsavEeWStvAm3pigyA" name="result" content="result" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_YN-XcodHEeK7oqVL4jKPeQ" name="result" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_YN-XcIdHEeK7oqVL4jKPeQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Pn3IIYdFEeK7oqVL4jKPeQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Pn3IIodFEeK7oqVL4jKPeQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b1BWbzpTEeSntPZ4lnT8Jg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b1BWcDpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b1BWcTpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_8nziIIdFEeK7oqVL4jKPeQ" documentation="A void automated task." name="Service Task 1" outgoing="_-MBt8IdFEeK7oqVL4jKPeQ" incoming="_7CQXkKNHEeK3qLDNhnWBJg" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_8nziJIdFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8nziIodFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8nziIYdFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8nziI4dFEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8nziJYdFEeK7oqVL4jKPeQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8nziJodFEeK7oqVL4jKPeQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b1BWeDpTEeSntPZ4lnT8Jg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b1BWeTpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b1BWejpTEeSntPZ4lnT8Jg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_6gfuUaNHEeK3qLDNhnWBJg" documentation="A 1-second timer." name="Timer1" outgoing="_7CQXkKNHEeK3qLDNhnWBJg" incoming="_6jgmEKNHEeK3qLDNhnWBJg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7JTe8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7JTfMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7JTfcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7JTfsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_d7JTf8avEeWStvAm3pigyA" name="1000" content="1000" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_DL0pQKNUEeK3qLDNhnWBJg" documentation="Should we have a last human step?&#xD;&#xA;Default path is to end with a human step otherwise the process terminates automatically." name="Gateway1" outgoing="_GpFaUKNUEeK3qLDNhnWBJg _HJO6AKNUEeK3qLDNhnWBJg" incoming="_CVfeMKNUEeK3qLDNhnWBJg" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7JTgMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6MMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6McavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6MsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_Go0UkKNUEeK3qLDNhnWBJg" name="Terminate end event2" incoming="_GpFaUKNUEeK3qLDNhnWBJg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6M8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6NMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6NcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6NsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_JpDV8KNVEeK3qLDNhnWBJg" documentation="This is an asbtract task." name="Abstract Step" outgoing="_6jgmEKNHEeK3qLDNhnWBJg" incoming="_N1oEEKNVEeK3qLDNhnWBJg" useCardinality="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6O8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6PMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6PcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6PsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d7J6P8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d7J6QMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d7J6QcavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d7J6QsavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d7J6Q8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Q7zcQIdFEeK7oqVL4jKPeQ" documentation="This is meant to be a human lane." name="Human lane" actor="_cIzVoIdEEeK7oqVL4jKPeQ">
        <elements xmi:type="process:Task" xmi:id="_OGCJAIdFEeK7oqVL4jKPeQ" documentation="This step has a very short boundary timer (1 second)." name="Human Task with Boundary Timer" incoming="_-MBt8IdFEeK7oqVL4jKPeQ" useCardinality="true" overrideActorsOfTheLane="false" priority="4">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6RMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6RcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6RsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6R8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d7J6SMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d7J6ScavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d7J6SsavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d7J6S8avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d7J6TMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_Oh0GEIdFEeK7oqVL4jKPeQ" name="Boundary Timer1" outgoing="_PoLRMIdFEeK7oqVL4jKPeQ">
            <condition xmi:type="expression:Expression" xmi:id="_d7J6aMavEeWStvAm3pigyA" name="1000" content="1000" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ppyIMBvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d7J6acavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ppyILxvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__U4QIQwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Bc4RoKNIEeK3qLDNhnWBJg" documentation="This is the last step of this test process." name="Last Human Step" outgoing="_MmUrQKNIEeK3qLDNhnWBJg" incoming="_HJO6AKNUEeK3qLDNhnWBJg" useCardinality="true" overrideActorsOfTheLane="false" priority="3">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6UMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6UcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6UsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6U8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d7J6VMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d7J6VcavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d7J6VsavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d7J6V8avEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d7J6WMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ppyIOxvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d7J6asavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ppyIOhvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__U4QLQwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_MmK6QKNIEeK3qLDNhnWBJg" name="Terminate end event1" incoming="_MmUrQKNIEeK3qLDNhnWBJg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6N8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6OMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6OcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6OsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Nhcj0KNVEeK3qLDNhnWBJg" name="Start Step" outgoing="_N1oEEKNVEeK3qLDNhnWBJg" incoming="_NTpYYKNVEeK3qLDNhnWBJg" useCardinality="true" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6W8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6XMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6XcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6XsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d7J6X8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d7J6YMavEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d7J6YcavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d7J6YsavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d7J6Y8avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <form xmi:type="form:Form" xmi:id="_Wg6ZMKNVEeK3qLDNhnWBJg" name="Start_Step">
            <widgets xmi:type="form:FileWidget" xmi:id="_Wg6ZMaNVEeK3qLDNhnWBJg" name="MyDocument" document="_n4XpMIdGEeK7oqVL4jKPeQ" outputDocumentName="MyDocument">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Wg6ZMqNVEeK3qLDNhnWBJg" line="2"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d7J6dsavEeWStvAm3pigyA" name="My document" content="My document" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d7J6d8avEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d7J6eMavEeWStvAm3pigyA" name="MyDocument" content="MyDocument" type="DOCUMENT_REF_TYPE"/>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d7J6ecavEeWStvAm3pigyA" name="field_MyDocument" content="field_MyDocument" type="TYPE_INPUT" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                  <referencedElements xmi:type="form:FileWidget" xmi:id="__U420AwYEei-AeSrpwoQZQ" name="MyDocument"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d7J6e8avEeWStvAm3pigyA" type="DOCUMENT_CREATE_UPDATE"/>
              </action>
            </widgets>
            <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_Wg6ZNKNVEeK3qLDNhnWBJg" name="lastHumanStep">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d7J6fMavEeWStvAm3pigyA"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d7J6fcavEeWStvAm3pigyA" name="lastHumanStep" content="lastHumanStep" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="__U421AwYEei-AeSrpwoQZQ" name="lastHumanStep" dataType="_cHMMEYdEEeK7oqVL4jKPeQ"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d7J6f8avEeWStvAm3pigyA" name="Human last step?" content="Human last step?" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d7J6gMavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d7J6gcavEeWStvAm3pigyA" name="lastHumanStep" content="lastHumanStep" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="process:Data" xmi:id="__U422AwYEei-AeSrpwoQZQ" name="lastHumanStep" dataType="_cHMMEYdEEeK7oqVL4jKPeQ"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d7J6g8avEeWStvAm3pigyA" name="field_lastHumanStep" content="field_lastHumanStep" type="TYPE_INPUT" returnType="java.lang.Boolean">
                  <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="__U422gwYEei-AeSrpwoQZQ" name="lastHumanStep"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d7J6hcavEeWStvAm3pigyA" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:TextFormField" xmi:id="_Wg6ZRqNVEeK3qLDNhnWBJg" name="myMessage">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d7J6hsavEeWStvAm3pigyA" line="1"/>
              <inputExpression xmi:type="expression:Expression" xmi:id="_d7J6h8avEeWStvAm3pigyA" name="myMessage" content="myMessage" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="__U423gwYEei-AeSrpwoQZQ" documentation="My test message variable." name="myMessage" dataType="_cHMMFodEEeK7oqVL4jKPeQ"/>
              </inputExpression>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d7J6icavEeWStvAm3pigyA" name="My message" content="My message" returnTypeFixed="true"/>
              <action xmi:type="expression:Operation" xmi:id="_d7J6isavEeWStvAm3pigyA">
                <leftOperand xmi:type="expression:Expression" xmi:id="_d7J6i8avEeWStvAm3pigyA" name="myMessage" content="myMessage" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="__U424gwYEei-AeSrpwoQZQ" documentation="My test message variable." name="myMessage" dataType="_cHMMFodEEeK7oqVL4jKPeQ"/>
                </leftOperand>
                <rightOperand xmi:type="expression:Expression" xmi:id="_d7J6jcavEeWStvAm3pigyA" name="field_myMessage" content="field_myMessage" type="TYPE_INPUT">
                  <referencedElements xmi:type="form:TextFormField" xmi:id="__U425AwYEei-AeSrpwoQZQ" name="myMessage"/>
                </rightOperand>
                <operator xmi:type="expression:Operator" xmi:id="_d7J6j8avEeWStvAm3pigyA" type="ASSIGNMENT"/>
              </action>
            </widgets>
            <widgets xmi:type="form:SubmitFormButton" xmi:id="_Wg7AT6NVEeK3qLDNhnWBJg" name="Submit1">
              <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_d7J6kMavEeWStvAm3pigyA" line="3"/>
              <displayLabel xmi:type="expression:Expression" xmi:id="_d7J6kcavEeWStvAm3pigyA" name="Submit" content="Submit" returnTypeFixed="true"/>
            </widgets>
            <pageLabel xmi:type="expression:Expression" xmi:id="_d7J6dMavEeWStvAm3pigyA" name="Start Step" content="Start Step" returnTypeFixed="true"/>
          </form>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6ZcavEeWStvAm3pigyA" content=""/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ppyISBvNEeWwB5BI7jdhZw" type="LEGACY">
            <targetForm xmi:type="expression:Expression" xmi:id="_d7J6a8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ppyIRxvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__U42vQwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_cJU6EIdEEeK7oqVL4jKPeQ" name="Start1" outgoing="_NTpYYKNVEeK3qLDNhnWBJg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_d7J6ksavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d7J6k8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d7J6lMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d7J6lcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_ABBN0JU1EeK8V-gUMmWlsA" path="_cHqtMIdEEeK7oqVL4jKPeQ/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_cH0eModEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_cH0eMYdEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_ABB04JU1EeK8V-gUMmWlsA" path="_cHqtMIdEEeK7oqVL4jKPeQ/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_ABB04pU1EeK8V-gUMmWlsA" path="_cHqtMIdEEeK7oqVL4jKPeQ/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_ABB04ZU1EeK8V-gUMmWlsA" path="_cHqtMIdEEeK7oqVL4jKPeQ/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_mdp-sIdGEeK7oqVL4jKPeQ" documentation="My test message variable." name="myMessage" dataType="_cHMMFodEEeK7oqVL4jKPeQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d7JTecavEeWStvAm3pigyA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_P68nQKNUEeK3qLDNhnWBJg" name="lastHumanStep" dataType="_cHMMEYdEEeK7oqVL4jKPeQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_d7JTesavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_cH0eNIdEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_cH0eM4dEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ppyH3xvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_d7J6bMavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_cH0eNYdEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ppyH4BvNEeWwB5BI7jdhZw" type="LEGACY">
        <targetForm xmi:type="expression:Expression" xmi:id="_d7J6bcavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_cH0eMIdEEeK7oqVL4jKPeQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PoLRMIdFEeK7oqVL4jKPeQ" target="_Pn1S8IdFEeK7oqVL4jKPeQ" source="_Oh0GEIdFEeK7oqVL4jKPeQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PoLRMYdFEeK7oqVL4jKPeQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6l8avEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-MBt8IdFEeK7oqVL4jKPeQ" target="_OGCJAIdFEeK7oqVL4jKPeQ" source="_8nziIIdFEeK7oqVL4jKPeQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-MBt8YdFEeK7oqVL4jKPeQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6mcavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6jgmEKNHEeK3qLDNhnWBJg" target="_6gfuUaNHEeK3qLDNhnWBJg" source="_JpDV8KNVEeK3qLDNhnWBJg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6jhNIKNHEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6m8avEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7CQXkKNHEeK3qLDNhnWBJg" target="_8nziIIdFEeK7oqVL4jKPeQ" source="_6gfuUaNHEeK3qLDNhnWBJg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7CQ-oKNHEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6ncavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MmUrQKNIEeK3qLDNhnWBJg" target="_MmK6QKNIEeK3qLDNhnWBJg" source="_Bc4RoKNIEeK3qLDNhnWBJg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MmUrQaNIEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6n8avEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CVfeMKNUEeK3qLDNhnWBJg" target="_DL0pQKNUEeK3qLDNhnWBJg" source="_Pn1S8IdFEeK7oqVL4jKPeQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CVfeMaNUEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6ocavEeWStvAm3pigyA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GpFaUKNUEeK3qLDNhnWBJg" target="_Go0UkKNUEeK3qLDNhnWBJg" source="_DL0pQKNUEeK3qLDNhnWBJg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GpFaUaNUEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6o8avEeWStvAm3pigyA" name="!lastHumanStep" content="!lastHumanStep" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="__U42-gwYEei-AeSrpwoQZQ" name="lastHumanStep" dataType="_cHMMEYdEEeK7oqVL4jKPeQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HJO6AKNUEeK3qLDNhnWBJg" target="_Bc4RoKNIEeK3qLDNhnWBJg" source="_DL0pQKNUEeK3qLDNhnWBJg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HJPhEKNUEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6psavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NTpYYKNVEeK3qLDNhnWBJg" target="_Nhcj0KNVEeK3qLDNhnWBJg" source="_cJU6EIdEEeK7oqVL4jKPeQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NTp_cKNVEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6qMavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N1oEEKNVEeK3qLDNhnWBJg" target="_JpDV8KNVEeK3qLDNhnWBJg" source="_Nhcj0KNVEeK3qLDNhnWBJg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N1oEEaNVEeK3qLDNhnWBJg"/>
        <condition xmi:type="expression:Expression" xmi:id="_d7J6qsavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_cIzVoIdEEeK7oqVL4jKPeQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_04R8wMRxEeK9cI0sZ_vRbQ" name="Selenium" version="6.0.0-ga-005" username="william.jobs" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_04Sj08RxEeK9cI0sZ_vRbQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_04Sj1MRxEeK9cI0sZ_vRbQ" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_04Sj1sRxEeK9cI0sZ_vRbQ">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_04Sj2MRxEeK9cI0sZ_vRbQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_04Sj18RxEeK9cI0sZ_vRbQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_04Sj1cRxEeK9cI0sZ_vRbQ"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_04Sj2cRxEeK9cI0sZ_vRbQ" type="CONNECTOR" definitionId="scripting-groovy" definitionVersion="1.0.1" implementationId="scripting-groovy-impl" implementationVersion="1.0.11"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04R8wcRxEeK9cI0sZ_vRbQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04R8wsRxEeK9cI0sZ_vRbQ" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_04R8zMRxEeK9cI0sZ_vRbQ" id="scripting-groovy-impl-1.0.11">
            <fragments xmi:type="configuration:Fragment" xmi:id="_04R8zcRxEeK9cI0sZ_vRbQ" key="scripting-groovy-impl -- 1.0.11" value="bonita-connector-scripting-groovy-impl-1.0.11.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_04R8zsRxEeK9cI0sZ_vRbQ" key="scripting-groovy-impl -- 1.0.11" value="scripting-groovy-impl-1.0.11" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj0MRxEeK9cI0sZ_vRbQ" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj0cRxEeK9cI0sZ_vRbQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj0sRxEeK9cI0sZ_vRbQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj2sRxEeK9cI0sZ_vRbQ" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj28RxEeK9cI0sZ_vRbQ" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj3MRxEeK9cI0sZ_vRbQ" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_04Sj3cRxEeK9cI0sZ_vRbQ" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_ppyH4RvNEeWwB5BI7jdhZw"/>
      <documents xmi:type="process:Document" xmi:id="_n4XpMIdGEeK7oqVL4jKPeQ" documentation="This is my test document." name="MyDocument" defaultValueIdOfDocumentStore="testlink_user_manual.pdf" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_d7J6vsavEeWStvAm3pigyA" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_d7J6v8avEeWStvAm3pigyA" content=""/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_cHz3IIdEEeK7oqVL4jKPeQ">
        <name xmi:type="expression:Expression" xmi:id="_d7J6wMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d7J6wcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_cHz3I4dEEeK7oqVL4jKPeQ">
        <name xmi:type="expression:Expression" xmi:id="_d7J6wsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d7J6w8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_cHz3JodEEeK7oqVL4jKPeQ">
        <name xmi:type="expression:Expression" xmi:id="_d7J6xMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d7J6xcavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_cHz3KYdEEeK7oqVL4jKPeQ">
        <name xmi:type="expression:Expression" xmi:id="_d7J6xsavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d7J6x8avEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_cHz3LIdEEeK7oqVL4jKPeQ">
        <name xmi:type="expression:Expression" xmi:id="_d7J6yMavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_d7J6ycavEeWStvAm3pigyA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <formMapping xmi:type="process:FormMapping" xmi:id="_ppyHvRvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_d7J6bsavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </formMapping>
    <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ppyHvhvNEeWwB5BI7jdhZw" type="LEGACY">
      <targetForm xmi:type="expression:Expression" xmi:id="_d7J6b8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
    </overviewFormMapping>
    <datatypes xmi:type="process:BooleanType" xmi:id="_cHMMEYdEEeK7oqVL4jKPeQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_cHMMEodEEeK7oqVL4jKPeQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_cHMME4dEEeK7oqVL4jKPeQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_cHMMFIdEEeK7oqVL4jKPeQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_cHMMFYdEEeK7oqVL4jKPeQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_cHMMFodEEeK7oqVL4jKPeQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_cHMMF4dEEeK7oqVL4jKPeQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_cHMMGIdEEeK7oqVL4jKPeQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_uSy_XOGOEeOBRccffrPWDw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_cHMMGYdEEeK7oqVL4jKPeQ" type="Process" element="_cHMMEIdEEeK7oqVL4jKPeQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_cIbiMIdEEeK7oqVL4jKPeQ" type="2007" element="_cHqtMIdEEeK7oqVL4jKPeQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_cIcJQIdEEeK7oqVL4jKPeQ" type="5008" element="_cHqtMIdEEeK7oqVL4jKPeQ"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_cIcJQYdEEeK7oqVL4jKPeQ" type="7001" element="_cHqtMIdEEeK7oqVL4jKPeQ">
        <children xmi:type="notation:Node" xmi:id="_d7J63savEeWStvAm3pigyA" type="3007" element="_cI3AAIdEEeK7oqVL4jKPeQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_cI4OJYdEEeK7oqVL4jKPeQ" type="5007" element="_cI3AAIdEEeK7oqVL4jKPeQ"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_cI41MIdEEeK7oqVL4jKPeQ" type="7002" element="_cI3AAIdEEeK7oqVL4jKPeQ">
            <children xmi:type="notation:Shape" xmi:id="_Pn910IdFEeK7oqVL4jKPeQ" type="3027" element="_Pn1S8IdFEeK7oqVL4jKPeQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J6-cavEeWStvAm3pigyA" type="5017" element="_Pn1S8IdFEeK7oqVL4jKPeQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pn-c4IdFEeK7oqVL4jKPeQ" x="643" y="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8n0wQIdFEeK7oqVL4jKPeQ" type="3027" element="_8nziIIdFEeK7oqVL4jKPeQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J6-8avEeWStvAm3pigyA" type="5017" element="_8nziIIdFEeK7oqVL4jKPeQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8n0wQYdFEeK7oqVL4jKPeQ" x="453" y="84" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6g0ecKNHEeK3qLDNhnWBJg" type="3017" element="_6gfuUaNHEeK3qLDNhnWBJg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J6_cavEeWStvAm3pigyA" type="5032" element="_6gfuUaNHEeK3qLDNhnWBJg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6g1skaNHEeK3qLDNhnWBJg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6g0ecaNHEeK3qLDNhnWBJg" x="400" y="104"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DL2ecKNUEeK3qLDNhnWBJg" type="3008" element="_DL0pQKNUEeK3qLDNhnWBJg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7AMavEeWStvAm3pigyA" type="5026" element="_DL0pQKNUEeK3qLDNhnWBJg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DL3skKNUEeK3qLDNhnWBJg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DL2ecaNUEeK3qLDNhnWBJg" x="822" y="97" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Go3X4KNUEeK3qLDNhnWBJg" type="3062" element="_Go0UkKNUEeK3qLDNhnWBJg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7A8avEeWStvAm3pigyA" type="5090" element="_Go0UkKNUEeK3qLDNhnWBJg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Go3-8aNUEeK3qLDNhnWBJg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Go3X4aNUEeK3qLDNhnWBJg" x="1076" y="104"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JpFLIKNVEeK3qLDNhnWBJg" type="3006" element="_JpDV8KNVEeK3qLDNhnWBJg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7BsavEeWStvAm3pigyA" type="5006" element="_JpDV8KNVEeK3qLDNhnWBJg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JpFLIaNVEeK3qLDNhnWBJg" x="271" y="94" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_cI4OIYdEEeK7oqVL4jKPeQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_cI4OIodEEeK7oqVL4jKPeQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_cI4OI4dEEeK7oqVL4jKPeQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_cI41MYdEEeK7oqVL4jKPeQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cI4OJIdEEeK7oqVL4jKPeQ" x="-40" y="-20"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_d7J65savEeWStvAm3pigyA" type="3007" element="_Q7zcQIdFEeK7oqVL4jKPeQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q73GoIdFEeK7oqVL4jKPeQ" type="5007" element="_Q7zcQIdFEeK7oqVL4jKPeQ"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Q73tsIdFEeK7oqVL4jKPeQ" type="7002" element="_Q7zcQIdFEeK7oqVL4jKPeQ">
            <children xmi:type="notation:Shape" xmi:id="_OGFMUIdFEeK7oqVL4jKPeQ" type="3005" element="_OGCJAIdFEeK7oqVL4jKPeQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7CMavEeWStvAm3pigyA" type="5005" element="_OGCJAIdFEeK7oqVL4jKPeQ"/>
              <children xmi:type="notation:Shape" xmi:id="_Oh3wcIdFEeK7oqVL4jKPeQ" type="3043" element="_Oh0GEIdFEeK7oqVL4jKPeQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_d7J7C8avEeWStvAm3pigyA" type="5055" element="_Oh0GEIdFEeK7oqVL4jKPeQ">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Oh4XgYdFEeK7oqVL4jKPeQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Oh3wcYdFEeK7oqVL4jKPeQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OGFMUYdFEeK7oqVL4jKPeQ" x="453" y="81" width="182" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Bc6t4KNIEeK3qLDNhnWBJg" type="3005" element="_Bc4RoKNIEeK3qLDNhnWBJg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7DsavEeWStvAm3pigyA" type="5005" element="_Bc4RoKNIEeK3qLDNhnWBJg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Bc6t4aNIEeK3qLDNhnWBJg" x="879" y="112" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MmMvcKNIEeK3qLDNhnWBJg" type="3062" element="_MmK6QKNIEeK3qLDNhnWBJg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7EMavEeWStvAm3pigyA" type="5090" element="_MmK6QKNIEeK3qLDNhnWBJg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_MmNWgaNIEeK3qLDNhnWBJg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MmMvcaNIEeK3qLDNhnWBJg" x="1076" y="128"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NheZAKNVEeK3qLDNhnWBJg" type="3005" element="_Nhcj0KNVEeK3qLDNhnWBJg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7E8avEeWStvAm3pigyA" type="5005" element="_Nhcj0KNVEeK3qLDNhnWBJg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NheZAaNVEeK3qLDNhnWBJg" x="119" y="100" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cJXWUIdEEeK7oqVL4jKPeQ" type="3002" element="_cJU6EIdEEeK7oqVL4jKPeQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_d7J7FcavEeWStvAm3pigyA" type="5024" element="_cJU6EIdEEeK7oqVL4jKPeQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_cJXWU4dEEeK7oqVL4jKPeQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cJXWUYdEEeK7oqVL4jKPeQ" x="40" y="110"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Q72fkYdFEeK7oqVL4jKPeQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Q72fkodFEeK7oqVL4jKPeQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Q72fk4dFEeK7oqVL4jKPeQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Q73tsYdFEeK7oqVL4jKPeQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q72flIdFEeK7oqVL4jKPeQ" x="176" y="210"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_cIbiMYdEEeK7oqVL4jKPeQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_cIbiModEEeK7oqVL4jKPeQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_cIbiM4dEEeK7oqVL4jKPeQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_cIcJQodEEeK7oqVL4jKPeQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cIbiNIdEEeK7oqVL4jKPeQ"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_cHMMGodEEeK7oqVL4jKPeQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_PoNtcIdFEeK7oqVL4jKPeQ" type="4001" element="_PoLRMIdFEeK7oqVL4jKPeQ" source="_Oh3wcIdFEeK7oqVL4jKPeQ" target="_Pn910IdFEeK7oqVL4jKPeQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7GMavEeWStvAm3pigyA" type="6001" element="_PoLRMIdFEeK7oqVL4jKPeQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7GcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7GsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PoNtcodFEeK7oqVL4jKPeQ" points="[13, 0, -185, 307]$[167, 0, -31, 307]$[167, -282, -31, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-MEKMIdFEeK7oqVL4jKPeQ" type="4001" element="_-MBt8IdFEeK7oqVL4jKPeQ" source="_8n0wQIdFEeK7oqVL4jKPeQ" target="_OGFMUIdFEeK7oqVL4jKPeQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7HMavEeWStvAm3pigyA" type="6001" element="_-MBt8IdFEeK7oqVL4jKPeQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7HcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7HsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-MEKModFEeK7oqVL4jKPeQ" points="[-39, 29, 8, -213]$[-39, 197, 8, -45]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-MMGAIdFEeK7oqVL4jKPeQ" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6jmFoKNHEeK3qLDNhnWBJg" type="4001" element="_6jgmEKNHEeK3qLDNhnWBJg" source="_JpFLIKNVEeK3qLDNhnWBJg" target="_6g0ecKNHEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7IcavEeWStvAm3pigyA" type="6001" element="_6jgmEKNHEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7IsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7I8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6jmFoqNHEeK3qLDNhnWBJg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7CUB8KNHEeK3qLDNhnWBJg" type="4001" element="_7CQXkKNHEeK3qLDNhnWBJg" source="_6g0ecKNHEeK3qLDNhnWBJg" target="_8n0wQIdFEeK7oqVL4jKPeQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7JcavEeWStvAm3pigyA" type="6001" element="_7CQXkKNHEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7JsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7J8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7CUpAaNHEeK3qLDNhnWBJg" points="[-6, -4, -159, 11]$[203, 7, 50, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7CdL4KNHEeK3qLDNhnWBJg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MmV5YKNIEeK3qLDNhnWBJg" type="4001" element="_MmUrQKNIEeK3qLDNhnWBJg" source="_Bc6t4KNIEeK3qLDNhnWBJg" target="_MmMvcKNIEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7KsavEeWStvAm3pigyA" type="6001" element="_MmUrQKNIEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7K8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7LMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MmV5YqNIEeK3qLDNhnWBJg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CVgsUKNUEeK3qLDNhnWBJg" type="4001" element="_CVfeMKNUEeK3qLDNhnWBJg" source="_Pn910IdFEeK7oqVL4jKPeQ" target="_DL2ecKNUEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7LsavEeWStvAm3pigyA" type="6001" element="_CVfeMKNUEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7L8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7MMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CVgsUqNUEeK3qLDNhnWBJg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GpGocKNUEeK3qLDNhnWBJg" type="4001" element="_GpFaUKNUEeK3qLDNhnWBJg" source="_DL2ecKNUEeK3qLDNhnWBJg" target="_Go3X4KNUEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7MsavEeWStvAm3pigyA" type="6001" element="_GpFaUKNUEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7M8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7NMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GpGocqNUEeK3qLDNhnWBJg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HJoioKNUEeK3qLDNhnWBJg" type="4001" element="_HJO6AKNUEeK3qLDNhnWBJg" source="_DL2ecKNUEeK3qLDNhnWBJg" target="_Bc6t4KNIEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7NsavEeWStvAm3pigyA" type="6001" element="_HJO6AKNUEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7N8avEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7OMavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HJoioqNUEeK3qLDNhnWBJg" points="[-22, 13, -98, -237]$[-22, 261, -98, 11]$[14, 261, -62, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HJs0EKNUEeK3qLDNhnWBJg" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NTsbsKNVEeK3qLDNhnWBJg" type="4001" element="_NTpYYKNVEeK3qLDNhnWBJg" source="_cJXWUIdEEeK7oqVL4jKPeQ" target="_NheZAKNVEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7O8avEeWStvAm3pigyA" type="6001" element="_NTpYYKNVEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7PMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7PcavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NTsbsqNVEeK3qLDNhnWBJg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N1orIKNVEeK3qLDNhnWBJg" type="4001" element="_N1oEEKNVEeK3qLDNhnWBJg" source="_NheZAKNVEeK3qLDNhnWBJg" target="_JpFLIKNVEeK3qLDNhnWBJg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d7J7P8avEeWStvAm3pigyA" type="6001" element="_N1oEEKNVEeK3qLDNhnWBJg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d7J7QMavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d7J7QcavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N1orIqNVEeK3qLDNhnWBJg" points="[0, -9, -102, -6]$[105, -28, 3, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N1rucKNVEeK3qLDNhnWBJg" id="(1.0,0.56)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_WhN7MKNVEeK3qLDNhnWBJg" type="Form" element="_Wg6ZMKNVEeK3qLDNhnWBJg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_WhN7MaNVEeK3qLDNhnWBJg"/>
  </notation:Diagram>
</xmi:XMI>
