<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_VfsHkTMZEeKvsbYsrc8Gjw" name="WeatherDiagram" author="truc" bonitaVersion="7.8.0" bonitaModelVersion="7.8.0-002" configId="ACED000574001E576561746865724469616772616D372E382E302D303032372E382E307370">
    <elements xmi:type="process:Pool" xmi:id="_VlLEgDMZEeKvsbYsrc8Gjw" name="WeatherTest">
      <elements xmi:type="process:Lane" xmi:id="_Vn950DMZEeKvsbYsrc8Gjw" name="Employee lane" actor="_Vn6PcDMZEeKvsbYsrc8Gjw">
        <elements xmi:type="process:Task" xmi:id="_VoeQIDMZEeKvsbYsrc8Gjw" name="Show Weather" outgoing="_spvSsDMhEeKYJdGEEYJqbw" incoming="_DzRTwLYsEeKxxbFzg49gog" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_v2BkwMoMEeKZxthsZIoBCw" content=""/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_v2zn4MoMEeKZxthsZIoBCw" content=""/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_v3ZdwMoMEeKZxthsZIoBCw" content=""/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uMQucMoIEeKZxthsZIoBCw" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uMuBcMoIEeKZxthsZIoBCw" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b8q2eDpTEeSntPZ4lnT8Jg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b8q2eTpTEeSntPZ4lnT8Jg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b8q2ejpTEeSntPZ4lnT8Jg" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pzRbFBvNEeWwB5BI7jdhZw">
            <targetForm xmi:type="expression:Expression" xmi:id="_eDKmzcavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pzRbExvNEeWwB5BI7jdhZw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__06axQwYEei-AeSrpwoQZQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_VqcmEDMZEeKvsbYsrc8Gjw" name="Start1" outgoing="_ZfbLoMoLEeKZxthsZIoBCw">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_6ZKZ4scgEeixX8Pu4cJneQ" source="_mX2ssLYtEeKxxbFzg49gog"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_XmKE0DMZEeKvsbYsrc8Gjw" name="Terminate end event1" incoming="_spvSsDMhEeKYJdGEEYJqbw"/>
        <elements xmi:type="process:ServiceTask" xmi:id="_DGVVQLYsEeKxxbFzg49gog" name="Get Weather" outgoing="_DzRTwLYsEeKxxbFzg49gog" incoming="_ZfbLoMoLEeKZxthsZIoBCw" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eDKm1savEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eDKm18avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eDKm2MavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_t1tS0MoMEeKZxthsZIoBCw" name="callWeatherWS" definitionId="webservice" event="ON_ENTER" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_t1tS2MoMEeKZxthsZIoBCw" definitionId="webservice" version="1.0.1" modelVersion="6.4.0-005">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS2coMEeKZxthsZIoBCw" key="serviceNS">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm7savEeWStvAm3pigyA" name="Weather" content="Weather"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS28oMEeKZxthsZIoBCw" key="serviceName">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm78avEeWStvAm3pigyA" name="http://ws.cdyne.com/WeatherWS/" content="http://ws.cdyne.com/WeatherWS/"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS3coMEeKZxthsZIoBCw" key="portName">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm8MavEeWStvAm3pigyA" name="WeatherSoap12" content="WeatherSoap12"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS38oMEeKZxthsZIoBCw" key="envelope">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm8cavEeWStvAm3pigyA" name="&lt;pattern-expression>" content="&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?>&#xD;&#xA;&lt;soap12:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:soap12=&quot;http://www.w3.org/2003/05/soap-envelope&quot;>&#xD;&#xA;  &lt;soap12:Body>&#xD;&#xA;    &lt;GetCityForecastByZIP xmlns=&quot;http://ws.cdyne.com/WeatherWS/&quot;>&#xD;&#xA;      &lt;ZIP>${zipCode}&lt;/ZIP>&#xD;&#xA;    &lt;/GetCityForecastByZIP>&#xD;&#xA;  &lt;/soap12:Body>&#xD;&#xA;&lt;/soap12:Envelope>&#xD;&#xA;" type="TYPE_PATTERN">
                  <referencedElements xmi:type="process:Data" xmi:id="__06a_AwYEei-AeSrpwoQZQ" name="zipCode" dataType="_VfsupTMZEeKvsbYsrc8Gjw"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS48oMEeKZxthsZIoBCw" key="endpointAddress">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm88avEeWStvAm3pigyA" name="http://wsf.cdyne.com/WeatherWS/Weather.asmx" content="http://wsf.cdyne.com/WeatherWS/Weather.asmx"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS5coMEeKZxthsZIoBCw" key="binding">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm9MavEeWStvAm3pigyA" name="http://www.w3.org/2003/05/soap/bindings/HTTP/" content="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS58oMEeKZxthsZIoBCw" key="soapAction">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm9cavEeWStvAm3pigyA" name="http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP" content="http://ws.cdyne.com/WeatherWS/GetCityForecastByZIP"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS6coMEeKZxthsZIoBCw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm9savEeWStvAm3pigyA" name="" content=""/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1tS68oMEeKZxthsZIoBCw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm98avEeWStvAm3pigyA" name="" content=""/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1t54coMEeKZxthsZIoBCw" key="buildResponseDocumentEnvelope">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm-MavEeWStvAm3pigyA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1t548oMEeKZxthsZIoBCw" key="buildResponseDocumentBody">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm-cavEeWStvAm3pigyA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1t55coMEeKZxthsZIoBCw" key="printRequestAndResponse">
                <expression xmi:type="expression:Expression" xmi:id="_eDKm-savEeWStvAm3pigyA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_t1t558oMEeKZxthsZIoBCw" key="httpHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_t1t56MoMEeKZxthsZIoBCw"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_t1tS0coMEeKZxthsZIoBCw">
              <leftOperand xmi:type="expression:Expression" xmi:id="_eDKm_MavEeWStvAm3pigyA" name="weatherText" content="weatherText" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="__06bBwwYEei-AeSrpwoQZQ" name="weatherText" dataType="_VfsupTMZEeKvsbYsrc8Gjw"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_eDKm_savEeWStvAm3pigyA" name="weatherTextScript" content="import org.w3c.dom.Element;&#xD;&#xA;import org.w3c.dom.NodeList;&#xD;&#xA;&#xD;&#xA;StringBuilder sb = new StringBuilder();&#xD;&#xA;NodeList forecasts = responseDocumentBody.getElementsByTagName(&quot;Forecast&quot;);&#xD;&#xA;&#xD;&#xA;Element elForecast;&#xD;&#xA;for (int i = 0; i &lt; forecasts.length; i++) {&#xD;&#xA;&#x9;elForecast = (Element) forecasts.item(i);&#xD;&#xA;&#x9;sb.append(((NodeList) elForecast.getElementsByTagName(&quot;Date&quot;)).item(0).getTextContent());&#xD;&#xA;&#x9;sb.append(&quot; :: &quot;);&#xD;&#xA;&#x9;sb.append(((NodeList) elForecast.getElementsByTagName(&quot;Desciption&quot;)).item(0).getTextContent());&#xD;&#xA;&#x9;sb.append(&quot;&lt;br>&quot;);&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return sb.toString();&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_t1tS18oMEeKZxthsZIoBCw" name="responseDocumentBody" type="org.w3c.dom.Document"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_t1tS1coMEeKZxthsZIoBCw" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eDKm2savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eDKm28avEeWStvAm3pigyA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eDKm3MavEeWStvAm3pigyA" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eDKm3cavEeWStvAm3pigyA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eDKm3savEeWStvAm3pigyA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_mX2ssLYtEeKxxbFzg49gog" text="FIXME: this process has to be completed!"/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_az9dkDMZEeKvsbYsrc8Gjw" name="weatherText" dataType="_VfsupTMZEeKvsbYsrc8Gjw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_eDKmy8avEeWStvAm3pigyA" name="" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_s6aFAMoIEeKZxthsZIoBCw" name="zipCode" dataType="_VfsupTMZEeKvsbYsrc8Gjw">
        <defaultValue xmi:type="expression:Expression" xmi:id="_eDKmzMavEeWStvAm3pigyA" name="10012" content="10012"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_pzRbARvNEeWwB5BI7jdhZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_eDKmzsavEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_pzRbAhvNEeWwB5BI7jdhZw">
        <targetForm xmi:type="expression:Expression" xmi:id="_eDKmz8avEeWStvAm3pigyA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_spvSsDMhEeKYJdGEEYJqbw" target="_XmKE0DMZEeKvsbYsrc8Gjw" source="_VoeQIDMZEeKvsbYsrc8Gjw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_spv5wDMhEeKYJdGEEYJqbw"/>
        <condition xmi:type="expression:Expression" xmi:id="_eDKnAsavEeWStvAm3pigyA" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DzRTwLYsEeKxxbFzg49gog" target="_VoeQIDMZEeKvsbYsrc8Gjw" source="_DGVVQLYsEeKxxbFzg49gog">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DzR60LYsEeKxxbFzg49gog"/>
        <condition xmi:type="expression:Expression" xmi:id="_eDKnBMavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZfbLoMoLEeKZxthsZIoBCw" target="_DGVVQLYsEeKxxbFzg49gog" source="_VqcmEDMZEeKvsbYsrc8Gjw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZfcZwMoLEeKZxthsZIoBCw"/>
        <condition xmi:type="expression:Expression" xmi:id="_eDKnBsavEeWStvAm3pigyA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Vn6PcDMZEeKvsbYsrc8Gjw" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_4ppL8MoLEeKZxthsZIoBCw" name="Selenium" version="6.0.0-ga-005" username="william.jobs" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_4ppL_soLEeKZxthsZIoBCw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4ppL_8oLEeKZxthsZIoBCw" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_4ppMAcoLEeKZxthsZIoBCw">
              <group>/acme</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4ppMA8oLEeKZxthsZIoBCw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4ppMAsoLEeKZxthsZIoBCw"/>
            <users xmi:type="actormapping:Users" xmi:id="_4ppMAMoLEeKZxthsZIoBCw"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_4ppMBMoLEeKZxthsZIoBCw" type="CONNECTOR" definitionId="webservice" definitionVersion="1.0.0" implementationId="webservice-impl" implementationVersion="1.0.11"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppL8coLEeKZxthsZIoBCw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppL8soLEeKZxthsZIoBCw" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_4ppL88oLEeKZxthsZIoBCw" id="webservice-impl-1.0.10">
            <fragments xmi:type="configuration:Fragment" xmi:id="_4ppL9MoLEeKZxthsZIoBCw" key="webservice-impl -- 1.0.10" value="bonita-connector-webservice-impl-6.0.0-beta-014.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_4ppL9coLEeKZxthsZIoBCw" key="webservice-impl -- 1.0.10" value="jsr181-api-1.0-MR1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_4ppL9soLEeKZxthsZIoBCw" key="webservice-impl -- 1.0.10" value="webservice-impl-1.0.10" type="CONNECTOR"/>
          </children>
          <children xmi:type="configuration:FragmentContainer" xmi:id="_4ppL98oLEeKZxthsZIoBCw" id="webservice-impl-1.0.11">
            <fragments xmi:type="configuration:Fragment" xmi:id="_4ppL-MoLEeKZxthsZIoBCw" key="webservice-impl -- 1.0.11" value="bonita-connector-webservice-impl-6.0.0-rc2.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_4ppL-coLEeKZxthsZIoBCw" key="webservice-impl -- 1.0.11" value="jsr181-api-1.0-MR1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_jQ7QAMoNEeKZxthsZIoBCw" key="webservice-impl -- 1.0.11" value="webservice-impl-1.0.11" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppL-8oLEeKZxthsZIoBCw" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppL_MoLEeKZxthsZIoBCw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppL_coLEeKZxthsZIoBCw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppMBcoLEeKZxthsZIoBCw" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppMBsoLEeKZxthsZIoBCw" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppMB8oLEeKZxthsZIoBCw" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4ppMCMoLEeKZxthsZIoBCw" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_pzRbAxvNEeWwB5BI7jdhZw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_exhDKLFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_eDKnH8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eDKnIMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_exhDKbFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_eDKnIcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eDKnIsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_exhDKrFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_eDKnI8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eDKnJMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_exhDK7FvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_eDKnJcavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eDKnJsavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_exhDLLFvEeKWXunJ2vlrJw">
        <name xmi:type="expression:Expression" xmi:id="_eDKnJ8avEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_eDKnKMavEeWStvAm3pigyA" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_VfsuoDMZEeKvsbYsrc8Gjw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_VfsuoTMZEeKvsbYsrc8Gjw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_VfsuojMZEeKvsbYsrc8Gjw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_VfsuozMZEeKvsbYsrc8Gjw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_VfsupDMZEeKvsbYsrc8Gjw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_VfsupTMZEeKvsbYsrc8Gjw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_VfsupjMZEeKvsbYsrc8Gjw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_VfsupzMZEeKvsbYsrc8Gjw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_ueqRHOGOEeOBRccffrPWDw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_VfsuqDMZEeKvsbYsrc8Gjw" type="Process" element="_VfsHkTMZEeKvsbYsrc8Gjw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_VmJU4DMZEeKvsbYsrc8Gjw" type="2007" element="_VlLEgDMZEeKvsbYsrc8Gjw">
      <children xmi:type="notation:DecorationNode" xmi:id="_VmLKEDMZEeKvsbYsrc8Gjw" type="5008" element="_VlLEgDMZEeKvsbYsrc8Gjw"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_VmLKETMZEeKvsbYsrc8Gjw" type="7001" element="_VlLEgDMZEeKvsbYsrc8Gjw">
        <children xmi:type="notation:Node" xmi:id="_eDKnPsavEeWStvAm3pigyA" type="3007" element="_Vn950DMZEeKvsbYsrc8Gjw">
          <children xmi:type="notation:DecorationNode" xmi:id="_VoAWEDMZEeKvsbYsrc8Gjw" type="5007" element="_Vn950DMZEeKvsbYsrc8Gjw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VoAWETMZEeKvsbYsrc8Gjw" type="7002" element="_Vn950DMZEeKvsbYsrc8Gjw">
            <children xmi:type="notation:Shape" xmi:id="_VohTcDMZEeKvsbYsrc8Gjw" type="3005" element="_VoeQIDMZEeKvsbYsrc8Gjw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eDKnUMavEeWStvAm3pigyA" type="5005" element="_VoeQIDMZEeKvsbYsrc8Gjw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VohTcTMZEeKvsbYsrc8Gjw" x="423" y="150" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VqfCUDMZEeKvsbYsrc8Gjw" type="3002" element="_VqcmEDMZEeKvsbYsrc8Gjw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eDKnUsavEeWStvAm3pigyA" type="5024" element="_VqcmEDMZEeKvsbYsrc8Gjw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VqfpYTMZEeKvsbYsrc8Gjw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VqfCUTMZEeKvsbYsrc8Gjw" x="45" y="170"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XmL6ADMZEeKvsbYsrc8Gjw" type="3062" element="_XmKE0DMZEeKvsbYsrc8Gjw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_eDKnVcavEeWStvAm3pigyA" type="5090" element="_XmKE0DMZEeKvsbYsrc8Gjw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XmMhEDMZEeKvsbYsrc8Gjw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XmL6ATMZEeKvsbYsrc8Gjw" x="637" y="170"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DGjXsLYsEeKxxbFzg49gog" type="3027" element="_DGVVQLYsEeKxxbFzg49gog" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eDKnWMavEeWStvAm3pigyA" type="5017" element="_DGVVQLYsEeKxxbFzg49gog"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DGjXsbYsEeKxxbFzg49gog" x="195" y="151" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_eDKnSsavEeWStvAm3pigyA" type="3015" element="_mX2ssLYtEeKxxbFzg49gog">
              <children xmi:type="notation:DecorationNode" xmi:id="_mX6XELYtEeKxxbFzg49gog" type="5010" element="_mX2ssLYtEeKxxbFzg49gog"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_mX5wAbYtEeKxxbFzg49gog"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_mX5wArYtEeKxxbFzg49gog" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_mX5wA7YtEeKxxbFzg49gog"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mX5wBLYtEeKxxbFzg49gog" x="43" y="27" width="362"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Vn_vATMZEeKvsbYsrc8Gjw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Vn_vAjMZEeKvsbYsrc8Gjw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Vn_vAzMZEeKvsbYsrc8Gjw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VoAWEjMZEeKvsbYsrc8Gjw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Vn_vBDMZEeKvsbYsrc8Gjw" x="45" y="10" width="1555" height="284"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_VmJU4TMZEeKvsbYsrc8Gjw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_VmJU4jMZEeKvsbYsrc8Gjw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_VmJU4zMZEeKvsbYsrc8Gjw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_VmLKEjMZEeKvsbYsrc8Gjw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VmJU5DMZEeKvsbYsrc8Gjw"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_VfsuqTMZEeKvsbYsrc8Gjw"/>
    <edges xmi:type="notation:Connector" xmi:id="_sp5DsDMhEeKYJdGEEYJqbw" type="4001" element="_spvSsDMhEeKYJdGEEYJqbw" source="_VohTcDMZEeKvsbYsrc8Gjw" target="_XmL6ADMZEeKvsbYsrc8Gjw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eDKnXMavEeWStvAm3pigyA" type="6001" element="_spvSsDMhEeKYJdGEEYJqbw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eDKnXcavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eDKnXsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sp5DsjMhEeKYJdGEEYJqbw" points="[0, -11, -205, 0]$[190, -11, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sqA_gDMhEeKYJdGEEYJqbw" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DzU-ILYsEeKxxbFzg49gog" type="4001" element="_DzRTwLYsEeKxxbFzg49gog" source="_DGjXsLYsEeKxxbFzg49gog" target="_VohTcDMZEeKvsbYsrc8Gjw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eDKnYcavEeWStvAm3pigyA" type="6001" element="_DzRTwLYsEeKxxbFzg49gog">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eDKnYsavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eDKnY8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DzU-IrYsEeKxxbFzg49gog" points="[0, -6, -140, -8]$[71, -6, -69, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Dzc58LYsEeKxxbFzg49gog" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q8mqQLYtEeKxxbFzg49gog" type="4003" source="_eDKnSsavEeWStvAm3pigyA" target="_VqfCUDMZEeKvsbYsrc8Gjw">
      <styles xmi:type="notation:FontStyle" xmi:id="_eDKnZsavEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q8mqQrYtEeKxxbFzg49gog" points="[-142, 44, 120, -44]$[-263, 73, -1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q8sJ0LYtEeKxxbFzg49gog" id="(1.0,0.12)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZfkVkMoLEeKZxthsZIoBCw" type="4001" element="_ZfbLoMoLEeKZxthsZIoBCw" source="_VqfCUDMZEeKvsbYsrc8Gjw" target="_DGjXsLYsEeKxxbFzg49gog" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eDKnacavEeWStvAm3pigyA" type="6001" element="_ZfbLoMoLEeKZxthsZIoBCw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eDKnasavEeWStvAm3pigyA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eDKna8avEeWStvAm3pigyA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZfkVksoLEeKZxthsZIoBCw" points="[-1, -12, -247, -1]$[196, -12, -50, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZfsRYMoLEeKZxthsZIoBCw" id="(1.0,1.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
